// Code generated by ogen, DO NOT EDIT.

package api

import (
	"net/http"
	"net/url"
	"strings"

	"github.com/ogen-go/ogen/uri"
)

func (s *Server) cutPrefix(path string) (string, bool) {
	prefix := s.cfg.Prefix
	if prefix == "" {
		return path, true
	}
	if !strings.HasPrefix(path, prefix) {
		// Prefix doesn't match.
		return "", false
	}
	// Cut prefix from the path.
	return strings.TrimPrefix(path, prefix), true
}

// ServeHTTP serves http request as defined by OpenAPI v3 specification,
// calling handler that matches the path or returning not found error.
func (s *Server) ServeHTTP(w http.ResponseWriter, r *http.Request) {
	elem := r.URL.Path
	elemIsEscaped := false
	if rawPath := r.URL.RawPath; rawPath != "" {
		if normalized, ok := uri.NormalizeEscapedPath(rawPath); ok {
			elem = normalized
			elemIsEscaped = strings.ContainsRune(elem, '%')
		}
	}

	elem, ok := s.cutPrefix(elem)
	if !ok || len(elem) == 0 {
		s.notFound(w, r)
		return
	}
	args := [2]string{}

	// Static code generated router with unwrapped path search.
	switch {
	default:
		if len(elem) == 0 {
			break
		}
		switch elem[0] {
		case '/': // Prefix: "/api/v1/progression"

			if l := len("/api/v1/progression"); len(elem) >= l && elem[0:l] == "/api/v1/progression" {
				elem = elem[l:]
			} else {
				break
			}

			if len(elem) == 0 {
				break
			}
			switch elem[0] {
			case '-': // Prefix: "-domain/health"

				if l := len("-domain/health"); len(elem) >= l && elem[0:l] == "-domain/health" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					switch r.Method {
					case "GET":
						s.handleProgressionDomainHealthCheckRequest([0]string{}, elemIsEscaped, w, r)
					default:
						s.notAllowed(w, r, "GET")
					}

					return
				}
				switch elem[0] {
				case '/': // Prefix: "/"

					if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						break
					}
					switch elem[0] {
					case 'b': // Prefix: "batch"

						if l := len("batch"); len(elem) >= l && elem[0:l] == "batch" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							// Leaf node.
							switch r.Method {
							case "POST":
								s.handleBatchHealthCheckRequest([0]string{}, elemIsEscaped, w, r)
							default:
								s.notAllowed(w, r, "POST")
							}

							return
						}

					case 'w': // Prefix: "ws"

						if l := len("ws"); len(elem) >= l && elem[0:l] == "ws" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							// Leaf node.
							switch r.Method {
							case "GET":
								s.handleHealthWebSocketRequest([0]string{}, elemIsEscaped, w, r)
							default:
								s.notAllowed(w, r, "GET")
							}

							return
						}

					}

				}

			case '/': // Prefix: "/"

				if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					break
				}
				switch elem[0] {
				case 'c': // Prefix: "characters/"

					if l := len("characters/"); len(elem) >= l && elem[0:l] == "characters/" {
						elem = elem[l:]
					} else {
						break
					}

					// Param: "characterId"
					// Match until "/"
					idx := strings.IndexByte(elem, '/')
					if idx < 0 {
						idx = len(elem)
					}
					args[0] = elem[:idx]
					elem = elem[idx:]

					if len(elem) == 0 {
						switch r.Method {
						case "GET":
							s.handleProgressionGetCharacterProgressionRequest([1]string{
								args[0],
							}, elemIsEscaped, w, r)
						default:
							s.notAllowed(w, r, "GET")
						}

						return
					}
					switch elem[0] {
					case '/': // Prefix: "/"

						if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							break
						}
						switch elem[0] {
						case 'a': // Prefix: "attributes"

							if l := len("attributes"); len(elem) >= l && elem[0:l] == "attributes" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								// Leaf node.
								switch r.Method {
								case "POST":
									s.handleProgressionAllocateAttributePointsRequest([1]string{
										args[0],
									}, elemIsEscaped, w, r)
								default:
									s.notAllowed(w, r, "POST")
								}

								return
							}

						case 'e': // Prefix: "experience"

							if l := len("experience"); len(elem) >= l && elem[0:l] == "experience" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								// Leaf node.
								switch r.Method {
								case "POST":
									s.handleProgressionGrantExperienceRequest([1]string{
										args[0],
									}, elemIsEscaped, w, r)
								default:
									s.notAllowed(w, r, "POST")
								}

								return
							}

						case 'l': // Prefix: "level-up"

							if l := len("level-up"); len(elem) >= l && elem[0:l] == "level-up" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								// Leaf node.
								switch r.Method {
								case "POST":
									s.handleProgressionLevelUpCharacterRequest([1]string{
										args[0],
									}, elemIsEscaped, w, r)
								default:
									s.notAllowed(w, r, "POST")
								}

								return
							}

						case 'r': // Prefix: "recalculate"

							if l := len("recalculate"); len(elem) >= l && elem[0:l] == "recalculate" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								// Leaf node.
								switch r.Method {
								case "POST":
									s.handleProgressionRecalculateCharacterStatsRequest([1]string{
										args[0],
									}, elemIsEscaped, w, r)
								default:
									s.notAllowed(w, r, "POST")
								}

								return
							}

						case 's': // Prefix: "skills"

							if l := len("skills"); len(elem) >= l && elem[0:l] == "skills" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								switch r.Method {
								case "GET":
									s.handleProgressionGetCharacterSkillsRequest([1]string{
										args[0],
									}, elemIsEscaped, w, r)
								default:
									s.notAllowed(w, r, "GET")
								}

								return
							}
							switch elem[0] {
							case '/': // Prefix: "/"

								if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
									elem = elem[l:]
								} else {
									break
								}

								// Param: "skillId"
								// Leaf parameter, slashes are prohibited
								idx := strings.IndexByte(elem, '/')
								if idx >= 0 {
									break
								}
								args[1] = elem
								elem = ""

								if len(elem) == 0 {
									// Leaf node.
									switch r.Method {
									case "POST":
										s.handleProgressionUpgradeSkillRequest([2]string{
											args[0],
											args[1],
										}, elemIsEscaped, w, r)
									default:
										s.notAllowed(w, r, "POST")
									}

									return
								}

							}

						}

					}

				case 'l': // Prefix: "levels/"

					if l := len("levels/"); len(elem) >= l && elem[0:l] == "levels/" {
						elem = elem[l:]
					} else {
						break
					}

					// Param: "level"
					// Match until "/"
					idx := strings.IndexByte(elem, '/')
					if idx < 0 {
						idx = len(elem)
					}
					args[0] = elem[:idx]
					elem = elem[idx:]

					if len(elem) == 0 {
						break
					}
					switch elem[0] {
					case '/': // Prefix: "/requirements"

						if l := len("/requirements"); len(elem) >= l && elem[0:l] == "/requirements" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							// Leaf node.
							switch r.Method {
							case "GET":
								s.handleProgressionGetLevelRequirementsRequest([1]string{
									args[0],
								}, elemIsEscaped, w, r)
							default:
								s.notAllowed(w, r, "GET")
							}

							return
						}

					}

				case 's': // Prefix: "skill"

					if l := len("skill"); len(elem) >= l && elem[0:l] == "skill" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						break
					}
					switch elem[0] {
					case '-': // Prefix: "-info/"

						if l := len("-info/"); len(elem) >= l && elem[0:l] == "-info/" {
							elem = elem[l:]
						} else {
							break
						}

						// Param: "skillId"
						// Leaf parameter, slashes are prohibited
						idx := strings.IndexByte(elem, '/')
						if idx >= 0 {
							break
						}
						args[0] = elem
						elem = ""

						if len(elem) == 0 {
							// Leaf node.
							switch r.Method {
							case "GET":
								s.handleProgressionGetSkillInfoRequest([1]string{
									args[0],
								}, elemIsEscaped, w, r)
							default:
								s.notAllowed(w, r, "GET")
							}

							return
						}

					case 's': // Prefix: "s/"

						if l := len("s/"); len(elem) >= l && elem[0:l] == "s/" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							break
						}
						switch elem[0] {
						case 'e': // Prefix: "experience/add"
							origElem := elem
							if l := len("experience/add"); len(elem) >= l && elem[0:l] == "experience/add" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								// Leaf node.
								switch r.Method {
								case "POST":
									s.handleAddSkillExperienceRequest([0]string{}, elemIsEscaped, w, r)
								default:
									s.notAllowed(w, r, "POST")
								}

								return
							}

							elem = origElem
						case 't': // Prefix: "tree/"
							origElem := elem
							if l := len("tree/"); len(elem) >= l && elem[0:l] == "tree/" {
								elem = elem[l:]
							} else {
								break
							}

							// Param: "playerId"
							// Leaf parameter, slashes are prohibited
							idx := strings.IndexByte(elem, '/')
							if idx >= 0 {
								break
							}
							args[0] = elem
							elem = ""

							if len(elem) == 0 {
								// Leaf node.
								switch r.Method {
								case "GET":
									s.handleGetSkillTreeRequest([1]string{
										args[0],
									}, elemIsEscaped, w, r)
								default:
									s.notAllowed(w, r, "GET")
								}

								return
							}

							elem = origElem
						case 'u': // Prefix: "unlock"
							origElem := elem
							if l := len("unlock"); len(elem) >= l && elem[0:l] == "unlock" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								// Leaf node.
								switch r.Method {
								case "POST":
									s.handleUnlockSkillRequest([0]string{}, elemIsEscaped, w, r)
								default:
									s.notAllowed(w, r, "POST")
								}

								return
							}

							elem = origElem
						}
						// Param: "playerId"
						// Leaf parameter, slashes are prohibited
						idx := strings.IndexByte(elem, '/')
						if idx >= 0 {
							break
						}
						args[0] = elem
						elem = ""

						if len(elem) == 0 {
							// Leaf node.
							switch r.Method {
							case "GET":
								s.handleGetPlayerSkillsRequest([1]string{
									args[0],
								}, elemIsEscaped, w, r)
							default:
								s.notAllowed(w, r, "GET")
							}

							return
						}

					}

				}

			}

		}
	}
	s.notFound(w, r)
}

// Route is route object.
type Route struct {
	name           string
	summary        string
	operationID    string
	operationGroup string
	pathPattern    string
	count          int
	args           [2]string
}

// Name returns ogen operation name.
//
// It is guaranteed to be unique and not empty.
func (r Route) Name() string {
	return r.name
}

// Summary returns OpenAPI summary.
func (r Route) Summary() string {
	return r.summary
}

// OperationID returns OpenAPI operationId.
func (r Route) OperationID() string {
	return r.operationID
}

// OperationGroup returns the x-ogen-operation-group value.
func (r Route) OperationGroup() string {
	return r.operationGroup
}

// PathPattern returns OpenAPI path.
func (r Route) PathPattern() string {
	return r.pathPattern
}

// Args returns parsed arguments.
func (r Route) Args() []string {
	return r.args[:r.count]
}

// FindRoute finds Route for given method and path.
//
// Note: this method does not unescape path or handle reserved characters in path properly. Use FindPath instead.
func (s *Server) FindRoute(method, path string) (Route, bool) {
	return s.FindPath(method, &url.URL{Path: path})
}

// FindPath finds Route for given method and URL.
func (s *Server) FindPath(method string, u *url.URL) (r Route, _ bool) {
	var (
		elem = u.Path
		args = r.args
	)
	if rawPath := u.RawPath; rawPath != "" {
		if normalized, ok := uri.NormalizeEscapedPath(rawPath); ok {
			elem = normalized
		}
		defer func() {
			for i, arg := range r.args[:r.count] {
				if unescaped, err := url.PathUnescape(arg); err == nil {
					r.args[i] = unescaped
				}
			}
		}()
	}

	elem, ok := s.cutPrefix(elem)
	if !ok {
		return r, false
	}

	// Static code generated router with unwrapped path search.
	switch {
	default:
		if len(elem) == 0 {
			break
		}
		switch elem[0] {
		case '/': // Prefix: "/api/v1/progression"

			if l := len("/api/v1/progression"); len(elem) >= l && elem[0:l] == "/api/v1/progression" {
				elem = elem[l:]
			} else {
				break
			}

			if len(elem) == 0 {
				break
			}
			switch elem[0] {
			case '-': // Prefix: "-domain/health"

				if l := len("-domain/health"); len(elem) >= l && elem[0:l] == "-domain/health" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					switch method {
					case "GET":
						r.name = ProgressionDomainHealthCheckOperation
						r.summary = "progression domain domain health check"
						r.operationID = "progression-domainHealthCheck"
						r.operationGroup = ""
						r.pathPattern = "/api/v1/progression-domain/health"
						r.args = args
						r.count = 0
						return r, true
					default:
						return
					}
				}
				switch elem[0] {
				case '/': // Prefix: "/"

					if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						break
					}
					switch elem[0] {
					case 'b': // Prefix: "batch"

						if l := len("batch"); len(elem) >= l && elem[0:l] == "batch" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							// Leaf node.
							switch method {
							case "POST":
								r.name = BatchHealthCheckOperation
								r.summary = "Batch health check for multiple domains"
								r.operationID = "batchHealthCheck"
								r.operationGroup = ""
								r.pathPattern = "/api/v1/progression-domain/health/batch"
								r.args = args
								r.count = 0
								return r, true
							default:
								return
							}
						}

					case 'w': // Prefix: "ws"

						if l := len("ws"); len(elem) >= l && elem[0:l] == "ws" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							// Leaf node.
							switch method {
							case "GET":
								r.name = HealthWebSocketOperation
								r.summary = "Real-time health monitoring WebSocket"
								r.operationID = "healthWebSocket"
								r.operationGroup = ""
								r.pathPattern = "/api/v1/progression-domain/health/ws"
								r.args = args
								r.count = 0
								return r, true
							default:
								return
							}
						}

					}

				}

			case '/': // Prefix: "/"

				if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					break
				}
				switch elem[0] {
				case 'c': // Prefix: "characters/"

					if l := len("characters/"); len(elem) >= l && elem[0:l] == "characters/" {
						elem = elem[l:]
					} else {
						break
					}

					// Param: "characterId"
					// Match until "/"
					idx := strings.IndexByte(elem, '/')
					if idx < 0 {
						idx = len(elem)
					}
					args[0] = elem[:idx]
					elem = elem[idx:]

					if len(elem) == 0 {
						switch method {
						case "GET":
							r.name = ProgressionGetCharacterProgressionOperation
							r.summary = "Получить информацию о прогрессии персонажа"
							r.operationID = "progressionGetCharacterProgression"
							r.operationGroup = ""
							r.pathPattern = "/api/v1/progression/characters/{characterId}"
							r.args = args
							r.count = 1
							return r, true
						default:
							return
						}
					}
					switch elem[0] {
					case '/': // Prefix: "/"

						if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							break
						}
						switch elem[0] {
						case 'a': // Prefix: "attributes"

							if l := len("attributes"); len(elem) >= l && elem[0:l] == "attributes" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								// Leaf node.
								switch method {
								case "POST":
									r.name = ProgressionAllocateAttributePointsOperation
									r.summary = "Распределить очки атрибутов"
									r.operationID = "progressionAllocateAttributePoints"
									r.operationGroup = ""
									r.pathPattern = "/api/v1/progression/characters/{characterId}/attributes"
									r.args = args
									r.count = 1
									return r, true
								default:
									return
								}
							}

						case 'e': // Prefix: "experience"

							if l := len("experience"); len(elem) >= l && elem[0:l] == "experience" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								// Leaf node.
								switch method {
								case "POST":
									r.name = ProgressionGrantExperienceOperation
									r.summary = "Начислить опыт персонажу"
									r.operationID = "progressionGrantExperience"
									r.operationGroup = ""
									r.pathPattern = "/api/v1/progression/characters/{characterId}/experience"
									r.args = args
									r.count = 1
									return r, true
								default:
									return
								}
							}

						case 'l': // Prefix: "level-up"

							if l := len("level-up"); len(elem) >= l && elem[0:l] == "level-up" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								// Leaf node.
								switch method {
								case "POST":
									r.name = ProgressionLevelUpCharacterOperation
									r.summary = "Повысить уровень персонажа"
									r.operationID = "progressionLevelUpCharacter"
									r.operationGroup = ""
									r.pathPattern = "/api/v1/progression/characters/{characterId}/level-up"
									r.args = args
									r.count = 1
									return r, true
								default:
									return
								}
							}

						case 'r': // Prefix: "recalculate"

							if l := len("recalculate"); len(elem) >= l && elem[0:l] == "recalculate" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								// Leaf node.
								switch method {
								case "POST":
									r.name = ProgressionRecalculateCharacterStatsOperation
									r.summary = "Пересчитать все статистики персонажа"
									r.operationID = "progressionRecalculateCharacterStats"
									r.operationGroup = ""
									r.pathPattern = "/api/v1/progression/characters/{characterId}/recalculate"
									r.args = args
									r.count = 1
									return r, true
								default:
									return
								}
							}

						case 's': // Prefix: "skills"

							if l := len("skills"); len(elem) >= l && elem[0:l] == "skills" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								switch method {
								case "GET":
									r.name = ProgressionGetCharacterSkillsOperation
									r.summary = "Получить навыки персонажа"
									r.operationID = "progressionGetCharacterSkills"
									r.operationGroup = ""
									r.pathPattern = "/api/v1/progression/characters/{characterId}/skills"
									r.args = args
									r.count = 1
									return r, true
								default:
									return
								}
							}
							switch elem[0] {
							case '/': // Prefix: "/"

								if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
									elem = elem[l:]
								} else {
									break
								}

								// Param: "skillId"
								// Leaf parameter, slashes are prohibited
								idx := strings.IndexByte(elem, '/')
								if idx >= 0 {
									break
								}
								args[1] = elem
								elem = ""

								if len(elem) == 0 {
									// Leaf node.
									switch method {
									case "POST":
										r.name = ProgressionUpgradeSkillOperation
										r.summary = "Повысить уровень навыка"
										r.operationID = "progressionUpgradeSkill"
										r.operationGroup = ""
										r.pathPattern = "/api/v1/progression/characters/{characterId}/skills/{skillId}"
										r.args = args
										r.count = 2
										return r, true
									default:
										return
									}
								}

							}

						}

					}

				case 'l': // Prefix: "levels/"

					if l := len("levels/"); len(elem) >= l && elem[0:l] == "levels/" {
						elem = elem[l:]
					} else {
						break
					}

					// Param: "level"
					// Match until "/"
					idx := strings.IndexByte(elem, '/')
					if idx < 0 {
						idx = len(elem)
					}
					args[0] = elem[:idx]
					elem = elem[idx:]

					if len(elem) == 0 {
						break
					}
					switch elem[0] {
					case '/': // Prefix: "/requirements"

						if l := len("/requirements"); len(elem) >= l && elem[0:l] == "/requirements" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							// Leaf node.
							switch method {
							case "GET":
								r.name = ProgressionGetLevelRequirementsOperation
								r.summary = "Получить требования к уровню"
								r.operationID = "progressionGetLevelRequirements"
								r.operationGroup = ""
								r.pathPattern = "/api/v1/progression/levels/{level}/requirements"
								r.args = args
								r.count = 1
								return r, true
							default:
								return
							}
						}

					}

				case 's': // Prefix: "skill"

					if l := len("skill"); len(elem) >= l && elem[0:l] == "skill" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						break
					}
					switch elem[0] {
					case '-': // Prefix: "-info/"

						if l := len("-info/"); len(elem) >= l && elem[0:l] == "-info/" {
							elem = elem[l:]
						} else {
							break
						}

						// Param: "skillId"
						// Leaf parameter, slashes are prohibited
						idx := strings.IndexByte(elem, '/')
						if idx >= 0 {
							break
						}
						args[0] = elem
						elem = ""

						if len(elem) == 0 {
							// Leaf node.
							switch method {
							case "GET":
								r.name = ProgressionGetSkillInfoOperation
								r.summary = "Получить информацию о навыке"
								r.operationID = "progressionGetSkillInfo"
								r.operationGroup = ""
								r.pathPattern = "/api/v1/progression/skill-info/{skillId}"
								r.args = args
								r.count = 1
								return r, true
							default:
								return
							}
						}

					case 's': // Prefix: "s/"

						if l := len("s/"); len(elem) >= l && elem[0:l] == "s/" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							break
						}
						switch elem[0] {
						case 'e': // Prefix: "experience/add"
							origElem := elem
							if l := len("experience/add"); len(elem) >= l && elem[0:l] == "experience/add" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								// Leaf node.
								switch method {
								case "POST":
									r.name = AddSkillExperienceOperation
									r.summary = "Добавить опыт навыку"
									r.operationID = "addSkillExperience"
									r.operationGroup = ""
									r.pathPattern = "/api/v1/progression/skills/experience/add"
									r.args = args
									r.count = 0
									return r, true
								default:
									return
								}
							}

							elem = origElem
						case 't': // Prefix: "tree/"
							origElem := elem
							if l := len("tree/"); len(elem) >= l && elem[0:l] == "tree/" {
								elem = elem[l:]
							} else {
								break
							}

							// Param: "playerId"
							// Leaf parameter, slashes are prohibited
							idx := strings.IndexByte(elem, '/')
							if idx >= 0 {
								break
							}
							args[0] = elem
							elem = ""

							if len(elem) == 0 {
								// Leaf node.
								switch method {
								case "GET":
									r.name = GetSkillTreeOperation
									r.summary = "Получить дерево навыков"
									r.operationID = "getSkillTree"
									r.operationGroup = ""
									r.pathPattern = "/api/v1/progression/skills/tree/{playerId}"
									r.args = args
									r.count = 1
									return r, true
								default:
									return
								}
							}

							elem = origElem
						case 'u': // Prefix: "unlock"
							origElem := elem
							if l := len("unlock"); len(elem) >= l && elem[0:l] == "unlock" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								// Leaf node.
								switch method {
								case "POST":
									r.name = UnlockSkillOperation
									r.summary = "Разблокировать навык"
									r.operationID = "unlockSkill"
									r.operationGroup = ""
									r.pathPattern = "/api/v1/progression/skills/unlock"
									r.args = args
									r.count = 0
									return r, true
								default:
									return
								}
							}

							elem = origElem
						}
						// Param: "playerId"
						// Leaf parameter, slashes are prohibited
						idx := strings.IndexByte(elem, '/')
						if idx >= 0 {
							break
						}
						args[0] = elem
						elem = ""

						if len(elem) == 0 {
							// Leaf node.
							switch method {
							case "GET":
								r.name = GetPlayerSkillsOperation
								r.summary = "Получить навыки персонажа"
								r.operationID = "getPlayerSkills"
								r.operationGroup = ""
								r.pathPattern = "/api/v1/progression/skills/{playerId}"
								r.args = args
								r.count = 1
								return r, true
							default:
								return
							}
						}

					}

				}

			}

		}
	}
	return r, false
}
