// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// CreateModel implements createModel operation.
	//
	// Create new ML model.
	//
	// POST /ml/models
	CreateModel(ctx context.Context, req *CreateModelRequest) (CreateModelRes, error)
	// DeleteModel implements deleteModel operation.
	//
	// Delete ML model.
	//
	// DELETE /ml/models/{modelId}
	DeleteModel(ctx context.Context, params DeleteModelParams) error
	// GetBatchHealth implements getBatchHealth operation.
	//
	// Get batch health status for all ML models.
	//
	// GET /health/batch
	GetBatchHealth(ctx context.Context) (*BatchHealthResponse, error)
	// GetHealth implements getHealth operation.
	//
	// Get service health status.
	//
	// GET /health
	GetHealth(ctx context.Context) (*HealthResponse, error)
	// GetModel implements getModel operation.
	//
	// Get ML model details.
	//
	// GET /ml/models/{modelId}
	GetModel(ctx context.Context, params GetModelParams) (GetModelRes, error)
	// GetModelAnalytics implements getModelAnalytics operation.
	//
	// Get ML model performance analytics.
	//
	// GET /ml/analytics/models
	GetModelAnalytics(ctx context.Context, params GetModelAnalyticsParams) (*ModelAnalyticsResponse, error)
	// GetPredictionAnalytics implements getPredictionAnalytics operation.
	//
	// Get prediction usage analytics.
	//
	// GET /ml/analytics/predictions
	GetPredictionAnalytics(ctx context.Context, params GetPredictionAnalyticsParams) (*PredictionAnalyticsResponse, error)
	// GetTrainingStatus implements getTrainingStatus operation.
	//
	// Get training job status.
	//
	// GET /ml/train/{jobId}/status
	GetTrainingStatus(ctx context.Context, params GetTrainingStatusParams) (*TrainingStatusResponse, error)
	// GetWebSocketHealth implements getWebSocketHealth operation.
	//
	// WebSocket health monitoring.
	//
	// GET /health/ws
	GetWebSocketHealth(ctx context.Context) (*WebSocketHealthMessage, error)
	// ListModels implements listModels operation.
	//
	// List all ML models.
	//
	// GET /ml/models
	ListModels(ctx context.Context, params ListModelsParams) (ListModelsRes, error)
	// MakeBatchPrediction implements makeBatchPrediction operation.
	//
	// Make batch predictions.
	//
	// POST /ml/predict/batch
	MakeBatchPrediction(ctx context.Context, req *BatchPredictionRequest) (*BatchPredictionResponse, error)
	// MakePrediction implements makePrediction operation.
	//
	// Make prediction using ML model.
	//
	// POST /ml/predict
	MakePrediction(ctx context.Context, req *PredictionRequest) (MakePredictionRes, error)
	// StartTraining implements startTraining operation.
	//
	// Start model training job.
	//
	// POST /ml/train
	StartTraining(ctx context.Context, req *TrainingRequest) (*TrainingJobResponse, error)
	// UpdateModel implements updateModel operation.
	//
	// Update ML model.
	//
	// PUT /ml/models/{modelId}
	UpdateModel(ctx context.Context, req *UpdateModelRequest, params UpdateModelParams) (*ModelResponse, error)
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h   Handler
	sec SecurityHandler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, sec SecurityHandler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		sec:        sec,
		baseServer: s,
	}, nil
}
