// Code generated by ogen, DO NOT EDIT.

package main

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// ApplyDamage implements applyDamage operation.
//
// Apply damage to enemy.
//
// POST /enemies/{enemy_id}/damage
func (UnimplementedHandler) ApplyDamage(ctx context.Context, req *DamageRequest, params ApplyDamageParams) (r *DamageResponse, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateSquad implements createSquad operation.
//
// Create new enemy squad.
//
// POST /squads
func (UnimplementedHandler) CreateSquad(ctx context.Context, req *CreateSquadRequest) (r *SquadResponse, _ error) {
	return r, ht.ErrNotImplemented
}

// GetActiveEnemies implements getActiveEnemies operation.
//
// Get all active AI enemies in zone.
//
// GET /enemies
func (UnimplementedHandler) GetActiveEnemies(ctx context.Context, params GetActiveEnemiesParams) (r *EnemyListResponse, _ error) {
	return r, ht.ErrNotImplemented
}

// GetActiveSquads implements getActiveSquads operation.
//
// Get all active enemy squads.
//
// GET /squads
func (UnimplementedHandler) GetActiveSquads(ctx context.Context, params GetActiveSquadsParams) (r *SquadListResponse, _ error) {
	return r, ht.ErrNotImplemented
}

// GetEnemy implements getEnemy operation.
//
// Get enemy details.
//
// GET /enemies/{enemy_id}
func (UnimplementedHandler) GetEnemy(ctx context.Context, params GetEnemyParams) (r GetEnemyRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetEnemyBehavior implements getEnemyBehavior operation.
//
// Get enemy behavior state.
//
// GET /enemies/{enemy_id}/behavior
func (UnimplementedHandler) GetEnemyBehavior(ctx context.Context, params GetEnemyBehaviorParams) (r *EnemyBehaviorResponse, _ error) {
	return r, ht.ErrNotImplemented
}

// GetHealth implements getHealth operation.
//
// Health check endpoint.
//
// GET /health
func (UnimplementedHandler) GetHealth(ctx context.Context) (r *HealthResponse, _ error) {
	return r, ht.ErrNotImplemented
}

// GetSquad implements getSquad operation.
//
// Get squad details.
//
// GET /squads/{squad_id}
func (UnimplementedHandler) GetSquad(ctx context.Context, params GetSquadParams) (r *SquadResponse, _ error) {
	return r, ht.ErrNotImplemented
}

// GetTelemetry implements getTelemetry operation.
//
// Get AI system telemetry.
//
// GET /telemetry
func (UnimplementedHandler) GetTelemetry(ctx context.Context, params GetTelemetryParams) (r *TelemetryResponse, _ error) {
	return r, ht.ErrNotImplemented
}

// GetZoneSync implements getZoneSync operation.
//
// Get zone synchronization state.
//
// GET /zones/{zone_id}/sync
func (UnimplementedHandler) GetZoneSync(ctx context.Context, params GetZoneSyncParams) (r *ZoneSyncResponse, _ error) {
	return r, ht.ErrNotImplemented
}

// RemoveEnemy implements removeEnemy operation.
//
// Remove enemy.
//
// DELETE /enemies/{enemy_id}
func (UnimplementedHandler) RemoveEnemy(ctx context.Context, params RemoveEnemyParams) error {
	return ht.ErrNotImplemented
}

// SpawnEnemy implements spawnEnemy operation.
//
// Spawn new AI enemy.
//
// POST /enemies
func (UnimplementedHandler) SpawnEnemy(ctx context.Context, req *SpawnEnemyRequest) (r *EnemyResponse, _ error) {
	return r, ht.ErrNotImplemented
}

// TriggerEnemyBehavior implements triggerEnemyBehavior operation.
//
// Trigger enemy behavior.
//
// POST /enemies/{enemy_id}/behavior
func (UnimplementedHandler) TriggerEnemyBehavior(ctx context.Context, req *TriggerBehaviorRequest, params TriggerEnemyBehaviorParams) error {
	return ht.ErrNotImplemented
}

// UpdateEnemy implements updateEnemy operation.
//
// Update enemy state.
//
// PUT /enemies/{enemy_id}
func (UnimplementedHandler) UpdateEnemy(ctx context.Context, req *UpdateEnemyRequest, params UpdateEnemyParams) (r *EnemyResponse, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateSquad implements updateSquad operation.
//
// Update squad coordination.
//
// PUT /squads/{squad_id}
func (UnimplementedHandler) UpdateSquad(ctx context.Context, req *UpdateSquadRequest, params UpdateSquadParams) (r *SquadResponse, _ error) {
	return r, ht.ErrNotImplemented
}

// UseEnemyAbility implements useEnemyAbility operation.
//
// Use enemy ability.
//
// POST /enemies/{enemy_id}/abilities
func (UnimplementedHandler) UseEnemyAbility(ctx context.Context, req *UseAbilityRequest, params UseEnemyAbilityParams) (r *AbilityResponse, _ error) {
	return r, ht.ErrNotImplemented
}
