// Code generated by ogen, DO NOT EDIT.

package api

import (
	"net/http"
	"net/url"

	"github.com/go-faster/errors"
	"github.com/google/uuid"
	"github.com/ogen-go/ogen/conv"
	"github.com/ogen-go/ogen/middleware"
	"github.com/ogen-go/ogen/ogenerrors"
	"github.com/ogen-go/ogen/uri"
	"github.com/ogen-go/ogen/validate"
)

// EndCombatSessionParams is parameters of endCombatSession operation.
type EndCombatSessionParams struct {
	SessionID uuid.UUID
}

func unpackEndCombatSessionParams(packed middleware.Parameters) (params EndCombatSessionParams) {
	{
		key := middleware.ParameterKey{
			Name: "session_id",
			In:   "path",
		}
		params.SessionID = packed[key].(uuid.UUID)
	}
	return params
}

func decodeEndCombatSessionParams(args [1]string, argsEscaped bool, r *http.Request) (params EndCombatSessionParams, _ error) {
	// Decode path: session_id.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "session_id",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToUUID(val)
				if err != nil {
					return err
				}

				params.SessionID = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "session_id",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// GetCombatSessionParams is parameters of getCombatSession operation.
type GetCombatSessionParams struct {
	SessionID uuid.UUID
}

func unpackGetCombatSessionParams(packed middleware.Parameters) (params GetCombatSessionParams) {
	{
		key := middleware.ParameterKey{
			Name: "session_id",
			In:   "path",
		}
		params.SessionID = packed[key].(uuid.UUID)
	}
	return params
}

func decodeGetCombatSessionParams(args [1]string, argsEscaped bool, r *http.Request) (params GetCombatSessionParams, _ error) {
	// Decode path: session_id.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "session_id",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToUUID(val)
				if err != nil {
					return err
				}

				params.SessionID = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "session_id",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// ListCombatSessionsParams is parameters of listCombatSessions operation.
type ListCombatSessionsParams struct {
	PlayerID OptUUID `json:",omitempty,omitzero"`
	// Количество элементов на странице.
	Limit OptInt `json:",omitempty,omitzero"`
}

func unpackListCombatSessionsParams(packed middleware.Parameters) (params ListCombatSessionsParams) {
	{
		key := middleware.ParameterKey{
			Name: "player_id",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.PlayerID = v.(OptUUID)
		}
	}
	{
		key := middleware.ParameterKey{
			Name: "limit",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.Limit = v.(OptInt)
		}
	}
	return params
}

func decodeListCombatSessionsParams(args [0]string, argsEscaped bool, r *http.Request) (params ListCombatSessionsParams, _ error) {
	q := uri.NewQueryDecoder(r.URL.Query())
	// Decode query: player_id.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "player_id",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotPlayerIDVal uuid.UUID
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToUUID(val)
					if err != nil {
						return err
					}

					paramsDotPlayerIDVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.PlayerID.SetTo(paramsDotPlayerIDVal)
				return nil
			}); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "player_id",
			In:   "query",
			Err:  err,
		}
	}
	// Set default value for query: limit.
	{
		val := int(50)
		params.Limit.SetTo(val)
	}
	// Decode query: limit.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "limit",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotLimitVal int
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToInt(val)
					if err != nil {
						return err
					}

					paramsDotLimitVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.Limit.SetTo(paramsDotLimitVal)
				return nil
			}); err != nil {
				return err
			}
			if err := func() error {
				if value, ok := params.Limit.Get(); ok {
					if err := func() error {
						if err := (validate.Int{
							MinSet:        true,
							Min:           1,
							MaxSet:        true,
							Max:           100,
							MinExclusive:  false,
							MaxExclusive:  false,
							MultipleOfSet: false,
							MultipleOf:    0,
							Pattern:       nil,
						}).Validate(int64(value)); err != nil {
							return errors.Wrap(err, "int")
						}
						return nil
					}(); err != nil {
						return err
					}
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "limit",
			In:   "query",
			Err:  err,
		}
	}
	return params, nil
}
