// Code generated by ogen, DO NOT EDIT.

package api

// setDefaults set default value of fields.
func (s *Channel) setDefaults() {
	{
		val := bool(false)
		s.IsTemporary.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *ChatMessage) setDefaults() {
	{
		val := ChatMessageContentType("TEXT")
		s.ContentType.SetTo(val)
	}
	{
		val := ChatMessagePriority("NORMAL")
		s.Priority.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *CreateChannelRequest) setDefaults() {
	{
		val := bool(false)
		s.IsTemporary.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *CreateQueueRequest) setDefaults() {
	{
		val := bool(false)
		s.Priority.SetTo(val)
	}
	{
		val := bool(true)
		s.Persistent.SetTo(val)
	}
	{
		val := int(10000)
		s.MaxSize.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *EnqueueMessageRequest) setDefaults() {
	{
		val := int(0)
		s.Priority.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *Notification) setDefaults() {
	{
		val := bool(false)
		s.Read.SetTo(val)
	}
}
