// Code generated by ogen, DO NOT EDIT.

package api

import (
	"net/http"
	"net/url"

	"github.com/go-faster/errors"
	"github.com/google/uuid"
	"github.com/ogen-go/ogen/conv"
	"github.com/ogen-go/ogen/middleware"
	"github.com/ogen-go/ogen/ogenerrors"
	"github.com/ogen-go/ogen/uri"
	"github.com/ogen-go/ogen/validate"
)

// AchievementClaimRewardsParams is parameters of achievementClaimRewards operation.
type AchievementClaimRewardsParams struct {
	// Achievement ID.
	AchievementID uuid.UUID
}

func unpackAchievementClaimRewardsParams(packed middleware.Parameters) (params AchievementClaimRewardsParams) {
	{
		key := middleware.ParameterKey{
			Name: "achievement_id",
			In:   "path",
		}
		params.AchievementID = packed[key].(uuid.UUID)
	}
	return params
}

func decodeAchievementClaimRewardsParams(args [1]string, argsEscaped bool, r *http.Request) (params AchievementClaimRewardsParams, _ error) {
	// Decode path: achievement_id.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "achievement_id",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToUUID(val)
				if err != nil {
					return err
				}

				params.AchievementID = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "achievement_id",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// AchievementDeleteAchievementParams is parameters of achievementDeleteAchievement operation.
type AchievementDeleteAchievementParams struct {
	// Achievement ID.
	AchievementID uuid.UUID
}

func unpackAchievementDeleteAchievementParams(packed middleware.Parameters) (params AchievementDeleteAchievementParams) {
	{
		key := middleware.ParameterKey{
			Name: "achievement_id",
			In:   "path",
		}
		params.AchievementID = packed[key].(uuid.UUID)
	}
	return params
}

func decodeAchievementDeleteAchievementParams(args [1]string, argsEscaped bool, r *http.Request) (params AchievementDeleteAchievementParams, _ error) {
	// Decode path: achievement_id.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "achievement_id",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToUUID(val)
				if err != nil {
					return err
				}

				params.AchievementID = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "achievement_id",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// AchievementGetAchievementParams is parameters of achievementGetAchievement operation.
type AchievementGetAchievementParams struct {
	// Achievement ID.
	AchievementID uuid.UUID
	// Character ID for progress context.
	CharacterID OptUUID `json:",omitempty,omitzero"`
}

func unpackAchievementGetAchievementParams(packed middleware.Parameters) (params AchievementGetAchievementParams) {
	{
		key := middleware.ParameterKey{
			Name: "achievement_id",
			In:   "path",
		}
		params.AchievementID = packed[key].(uuid.UUID)
	}
	{
		key := middleware.ParameterKey{
			Name: "character_id",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.CharacterID = v.(OptUUID)
		}
	}
	return params
}

func decodeAchievementGetAchievementParams(args [1]string, argsEscaped bool, r *http.Request) (params AchievementGetAchievementParams, _ error) {
	q := uri.NewQueryDecoder(r.URL.Query())
	// Decode path: achievement_id.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "achievement_id",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToUUID(val)
				if err != nil {
					return err
				}

				params.AchievementID = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "achievement_id",
			In:   "path",
			Err:  err,
		}
	}
	// Decode query: character_id.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "character_id",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotCharacterIDVal uuid.UUID
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToUUID(val)
					if err != nil {
						return err
					}

					paramsDotCharacterIDVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.CharacterID.SetTo(paramsDotCharacterIDVal)
				return nil
			}); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "character_id",
			In:   "query",
			Err:  err,
		}
	}
	return params, nil
}

// AchievementGetAnalyticsSummaryParams is parameters of achievementGetAnalyticsSummary operation.
type AchievementGetAnalyticsSummaryParams struct {
	// Character ID for personal analytics.
	CharacterID OptUUID `json:",omitempty,omitzero"`
	// Time period for analytics.
	Timeframe OptAchievementGetAnalyticsSummaryTimeframe `json:",omitempty,omitzero"`
	// Achievement category filter.
	Category OptAchievementGetAnalyticsSummaryCategory `json:",omitempty,omitzero"`
}

func unpackAchievementGetAnalyticsSummaryParams(packed middleware.Parameters) (params AchievementGetAnalyticsSummaryParams) {
	{
		key := middleware.ParameterKey{
			Name: "character_id",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.CharacterID = v.(OptUUID)
		}
	}
	{
		key := middleware.ParameterKey{
			Name: "timeframe",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.Timeframe = v.(OptAchievementGetAnalyticsSummaryTimeframe)
		}
	}
	{
		key := middleware.ParameterKey{
			Name: "category",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.Category = v.(OptAchievementGetAnalyticsSummaryCategory)
		}
	}
	return params
}

func decodeAchievementGetAnalyticsSummaryParams(args [0]string, argsEscaped bool, r *http.Request) (params AchievementGetAnalyticsSummaryParams, _ error) {
	q := uri.NewQueryDecoder(r.URL.Query())
	// Decode query: character_id.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "character_id",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotCharacterIDVal uuid.UUID
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToUUID(val)
					if err != nil {
						return err
					}

					paramsDotCharacterIDVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.CharacterID.SetTo(paramsDotCharacterIDVal)
				return nil
			}); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "character_id",
			In:   "query",
			Err:  err,
		}
	}
	// Set default value for query: timeframe.
	{
		val := AchievementGetAnalyticsSummaryTimeframe("week")
		params.Timeframe.SetTo(val)
	}
	// Decode query: timeframe.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "timeframe",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotTimeframeVal AchievementGetAnalyticsSummaryTimeframe
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToString(val)
					if err != nil {
						return err
					}

					paramsDotTimeframeVal = AchievementGetAnalyticsSummaryTimeframe(c)
					return nil
				}(); err != nil {
					return err
				}
				params.Timeframe.SetTo(paramsDotTimeframeVal)
				return nil
			}); err != nil {
				return err
			}
			if err := func() error {
				if value, ok := params.Timeframe.Get(); ok {
					if err := func() error {
						if err := value.Validate(); err != nil {
							return err
						}
						return nil
					}(); err != nil {
						return err
					}
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "timeframe",
			In:   "query",
			Err:  err,
		}
	}
	// Decode query: category.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "category",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotCategoryVal AchievementGetAnalyticsSummaryCategory
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToString(val)
					if err != nil {
						return err
					}

					paramsDotCategoryVal = AchievementGetAnalyticsSummaryCategory(c)
					return nil
				}(); err != nil {
					return err
				}
				params.Category.SetTo(paramsDotCategoryVal)
				return nil
			}); err != nil {
				return err
			}
			if err := func() error {
				if value, ok := params.Category.Get(); ok {
					if err := func() error {
						if err := value.Validate(); err != nil {
							return err
						}
						return nil
					}(); err != nil {
						return err
					}
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "category",
			In:   "query",
			Err:  err,
		}
	}
	return params, nil
}

// AchievementGetLeaderboardParams is parameters of achievementGetLeaderboard operation.
type AchievementGetLeaderboardParams struct {
	// Specific achievement ID for leaderboard.
	AchievementID OptUUID `json:",omitempty,omitzero"`
	// Achievement category for leaderboard.
	Category OptAchievementGetLeaderboardCategory `json:",omitempty,omitzero"`
	// Time period for leaderboard.
	Timeframe OptAchievementGetLeaderboardTimeframe `json:",omitempty,omitzero"`
	// Maximum number of leaderboard entries.
	Limit OptInt `json:",omitempty,omitzero"`
}

func unpackAchievementGetLeaderboardParams(packed middleware.Parameters) (params AchievementGetLeaderboardParams) {
	{
		key := middleware.ParameterKey{
			Name: "achievement_id",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.AchievementID = v.(OptUUID)
		}
	}
	{
		key := middleware.ParameterKey{
			Name: "category",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.Category = v.(OptAchievementGetLeaderboardCategory)
		}
	}
	{
		key := middleware.ParameterKey{
			Name: "timeframe",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.Timeframe = v.(OptAchievementGetLeaderboardTimeframe)
		}
	}
	{
		key := middleware.ParameterKey{
			Name: "limit",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.Limit = v.(OptInt)
		}
	}
	return params
}

func decodeAchievementGetLeaderboardParams(args [0]string, argsEscaped bool, r *http.Request) (params AchievementGetLeaderboardParams, _ error) {
	q := uri.NewQueryDecoder(r.URL.Query())
	// Decode query: achievement_id.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "achievement_id",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotAchievementIDVal uuid.UUID
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToUUID(val)
					if err != nil {
						return err
					}

					paramsDotAchievementIDVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.AchievementID.SetTo(paramsDotAchievementIDVal)
				return nil
			}); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "achievement_id",
			In:   "query",
			Err:  err,
		}
	}
	// Decode query: category.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "category",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotCategoryVal AchievementGetLeaderboardCategory
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToString(val)
					if err != nil {
						return err
					}

					paramsDotCategoryVal = AchievementGetLeaderboardCategory(c)
					return nil
				}(); err != nil {
					return err
				}
				params.Category.SetTo(paramsDotCategoryVal)
				return nil
			}); err != nil {
				return err
			}
			if err := func() error {
				if value, ok := params.Category.Get(); ok {
					if err := func() error {
						if err := value.Validate(); err != nil {
							return err
						}
						return nil
					}(); err != nil {
						return err
					}
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "category",
			In:   "query",
			Err:  err,
		}
	}
	// Set default value for query: timeframe.
	{
		val := AchievementGetLeaderboardTimeframe("month")
		params.Timeframe.SetTo(val)
	}
	// Decode query: timeframe.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "timeframe",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotTimeframeVal AchievementGetLeaderboardTimeframe
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToString(val)
					if err != nil {
						return err
					}

					paramsDotTimeframeVal = AchievementGetLeaderboardTimeframe(c)
					return nil
				}(); err != nil {
					return err
				}
				params.Timeframe.SetTo(paramsDotTimeframeVal)
				return nil
			}); err != nil {
				return err
			}
			if err := func() error {
				if value, ok := params.Timeframe.Get(); ok {
					if err := func() error {
						if err := value.Validate(); err != nil {
							return err
						}
						return nil
					}(); err != nil {
						return err
					}
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "timeframe",
			In:   "query",
			Err:  err,
		}
	}
	// Set default value for query: limit.
	{
		val := int(50)
		params.Limit.SetTo(val)
	}
	// Decode query: limit.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "limit",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotLimitVal int
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToInt(val)
					if err != nil {
						return err
					}

					paramsDotLimitVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.Limit.SetTo(paramsDotLimitVal)
				return nil
			}); err != nil {
				return err
			}
			if err := func() error {
				if value, ok := params.Limit.Get(); ok {
					if err := func() error {
						if err := (validate.Int{
							MinSet:        true,
							Min:           1,
							MaxSet:        true,
							Max:           100,
							MinExclusive:  false,
							MaxExclusive:  false,
							MultipleOfSet: false,
							MultipleOf:    0,
							Pattern:       nil,
						}).Validate(int64(value)); err != nil {
							return errors.Wrap(err, "int")
						}
						return nil
					}(); err != nil {
						return err
					}
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "limit",
			In:   "query",
			Err:  err,
		}
	}
	return params, nil
}

// AchievementGetProgressParams is parameters of achievementGetProgress operation.
type AchievementGetProgressParams struct {
	// Achievement ID.
	AchievementID uuid.UUID
	// Character ID.
	CharacterID uuid.UUID
}

func unpackAchievementGetProgressParams(packed middleware.Parameters) (params AchievementGetProgressParams) {
	{
		key := middleware.ParameterKey{
			Name: "achievement_id",
			In:   "path",
		}
		params.AchievementID = packed[key].(uuid.UUID)
	}
	{
		key := middleware.ParameterKey{
			Name: "character_id",
			In:   "query",
		}
		params.CharacterID = packed[key].(uuid.UUID)
	}
	return params
}

func decodeAchievementGetProgressParams(args [1]string, argsEscaped bool, r *http.Request) (params AchievementGetProgressParams, _ error) {
	q := uri.NewQueryDecoder(r.URL.Query())
	// Decode path: achievement_id.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "achievement_id",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToUUID(val)
				if err != nil {
					return err
				}

				params.AchievementID = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "achievement_id",
			In:   "path",
			Err:  err,
		}
	}
	// Decode query: character_id.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "character_id",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToUUID(val)
				if err != nil {
					return err
				}

				params.CharacterID = c
				return nil
			}); err != nil {
				return err
			}
		} else {
			return err
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "character_id",
			In:   "query",
			Err:  err,
		}
	}
	return params, nil
}

// AchievementListAchievementsParams is parameters of achievementListAchievements operation.
type AchievementListAchievementsParams struct {
	// Character ID (optional, returns unlocked achievements).
	CharacterID OptUUID `json:",omitempty,omitzero"`
	// Achievement category filter.
	Category OptAchievementListAchievementsCategory `json:",omitempty,omitzero"`
	// Achievement status filter.
	Status OptAchievementListAchievementsStatus `json:",omitempty,omitzero"`
	// Maximum number of achievements to return.
	Limit OptInt `json:",omitempty,omitzero"`
	// Number of achievements to skip.
	Offset OptInt `json:",omitempty,omitzero"`
}

func unpackAchievementListAchievementsParams(packed middleware.Parameters) (params AchievementListAchievementsParams) {
	{
		key := middleware.ParameterKey{
			Name: "character_id",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.CharacterID = v.(OptUUID)
		}
	}
	{
		key := middleware.ParameterKey{
			Name: "category",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.Category = v.(OptAchievementListAchievementsCategory)
		}
	}
	{
		key := middleware.ParameterKey{
			Name: "status",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.Status = v.(OptAchievementListAchievementsStatus)
		}
	}
	{
		key := middleware.ParameterKey{
			Name: "limit",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.Limit = v.(OptInt)
		}
	}
	{
		key := middleware.ParameterKey{
			Name: "offset",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.Offset = v.(OptInt)
		}
	}
	return params
}

func decodeAchievementListAchievementsParams(args [0]string, argsEscaped bool, r *http.Request) (params AchievementListAchievementsParams, _ error) {
	q := uri.NewQueryDecoder(r.URL.Query())
	// Decode query: character_id.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "character_id",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotCharacterIDVal uuid.UUID
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToUUID(val)
					if err != nil {
						return err
					}

					paramsDotCharacterIDVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.CharacterID.SetTo(paramsDotCharacterIDVal)
				return nil
			}); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "character_id",
			In:   "query",
			Err:  err,
		}
	}
	// Decode query: category.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "category",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotCategoryVal AchievementListAchievementsCategory
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToString(val)
					if err != nil {
						return err
					}

					paramsDotCategoryVal = AchievementListAchievementsCategory(c)
					return nil
				}(); err != nil {
					return err
				}
				params.Category.SetTo(paramsDotCategoryVal)
				return nil
			}); err != nil {
				return err
			}
			if err := func() error {
				if value, ok := params.Category.Get(); ok {
					if err := func() error {
						if err := value.Validate(); err != nil {
							return err
						}
						return nil
					}(); err != nil {
						return err
					}
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "category",
			In:   "query",
			Err:  err,
		}
	}
	// Decode query: status.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "status",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotStatusVal AchievementListAchievementsStatus
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToString(val)
					if err != nil {
						return err
					}

					paramsDotStatusVal = AchievementListAchievementsStatus(c)
					return nil
				}(); err != nil {
					return err
				}
				params.Status.SetTo(paramsDotStatusVal)
				return nil
			}); err != nil {
				return err
			}
			if err := func() error {
				if value, ok := params.Status.Get(); ok {
					if err := func() error {
						if err := value.Validate(); err != nil {
							return err
						}
						return nil
					}(); err != nil {
						return err
					}
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "status",
			In:   "query",
			Err:  err,
		}
	}
	// Set default value for query: limit.
	{
		val := int(20)
		params.Limit.SetTo(val)
	}
	// Decode query: limit.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "limit",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotLimitVal int
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToInt(val)
					if err != nil {
						return err
					}

					paramsDotLimitVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.Limit.SetTo(paramsDotLimitVal)
				return nil
			}); err != nil {
				return err
			}
			if err := func() error {
				if value, ok := params.Limit.Get(); ok {
					if err := func() error {
						if err := (validate.Int{
							MinSet:        true,
							Min:           1,
							MaxSet:        true,
							Max:           100,
							MinExclusive:  false,
							MaxExclusive:  false,
							MultipleOfSet: false,
							MultipleOf:    0,
							Pattern:       nil,
						}).Validate(int64(value)); err != nil {
							return errors.Wrap(err, "int")
						}
						return nil
					}(); err != nil {
						return err
					}
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "limit",
			In:   "query",
			Err:  err,
		}
	}
	// Set default value for query: offset.
	{
		val := int(0)
		params.Offset.SetTo(val)
	}
	// Decode query: offset.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "offset",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotOffsetVal int
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToInt(val)
					if err != nil {
						return err
					}

					paramsDotOffsetVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.Offset.SetTo(paramsDotOffsetVal)
				return nil
			}); err != nil {
				return err
			}
			if err := func() error {
				if value, ok := params.Offset.Get(); ok {
					if err := func() error {
						if err := (validate.Int{
							MinSet:        true,
							Min:           0,
							MaxSet:        false,
							Max:           0,
							MinExclusive:  false,
							MaxExclusive:  false,
							MultipleOfSet: false,
							MultipleOf:    0,
							Pattern:       nil,
						}).Validate(int64(value)); err != nil {
							return errors.Wrap(err, "int")
						}
						return nil
					}(); err != nil {
						return err
					}
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "offset",
			In:   "query",
			Err:  err,
		}
	}
	return params, nil
}

// AchievementUnlockAchievementParams is parameters of achievementUnlockAchievement operation.
type AchievementUnlockAchievementParams struct {
	// Achievement ID.
	AchievementID uuid.UUID
}

func unpackAchievementUnlockAchievementParams(packed middleware.Parameters) (params AchievementUnlockAchievementParams) {
	{
		key := middleware.ParameterKey{
			Name: "achievement_id",
			In:   "path",
		}
		params.AchievementID = packed[key].(uuid.UUID)
	}
	return params
}

func decodeAchievementUnlockAchievementParams(args [1]string, argsEscaped bool, r *http.Request) (params AchievementUnlockAchievementParams, _ error) {
	// Decode path: achievement_id.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "achievement_id",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToUUID(val)
				if err != nil {
					return err
				}

				params.AchievementID = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "achievement_id",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// AchievementUpdateAchievementParams is parameters of achievementUpdateAchievement operation.
type AchievementUpdateAchievementParams struct {
	// Achievement ID.
	AchievementID uuid.UUID
}

func unpackAchievementUpdateAchievementParams(packed middleware.Parameters) (params AchievementUpdateAchievementParams) {
	{
		key := middleware.ParameterKey{
			Name: "achievement_id",
			In:   "path",
		}
		params.AchievementID = packed[key].(uuid.UUID)
	}
	return params
}

func decodeAchievementUpdateAchievementParams(args [1]string, argsEscaped bool, r *http.Request) (params AchievementUpdateAchievementParams, _ error) {
	// Decode path: achievement_id.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "achievement_id",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToUUID(val)
				if err != nil {
					return err
				}

				params.AchievementID = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "achievement_id",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// AchievementUpdateProgressParams is parameters of achievementUpdateProgress operation.
type AchievementUpdateProgressParams struct {
	// Achievement ID.
	AchievementID uuid.UUID
	// Character ID.
	CharacterID uuid.UUID
}

func unpackAchievementUpdateProgressParams(packed middleware.Parameters) (params AchievementUpdateProgressParams) {
	{
		key := middleware.ParameterKey{
			Name: "achievement_id",
			In:   "path",
		}
		params.AchievementID = packed[key].(uuid.UUID)
	}
	{
		key := middleware.ParameterKey{
			Name: "character_id",
			In:   "query",
		}
		params.CharacterID = packed[key].(uuid.UUID)
	}
	return params
}

func decodeAchievementUpdateProgressParams(args [1]string, argsEscaped bool, r *http.Request) (params AchievementUpdateProgressParams, _ error) {
	q := uri.NewQueryDecoder(r.URL.Query())
	// Decode path: achievement_id.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "achievement_id",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToUUID(val)
				if err != nil {
					return err
				}

				params.AchievementID = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "achievement_id",
			In:   "path",
			Err:  err,
		}
	}
	// Decode query: character_id.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "character_id",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToUUID(val)
				if err != nil {
					return err
				}

				params.CharacterID = c
				return nil
			}); err != nil {
				return err
			}
		} else {
			return err
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "character_id",
			In:   "query",
			Err:  err,
		}
	}
	return params, nil
}

// GetAchievementRecommendationsParams is parameters of getAchievementRecommendations operation.
type GetAchievementRecommendationsParams struct {
	// Character ID for personalization.
	CharacterID uuid.UUID
	// Current gameplay focus area.
	CurrentFocus OptGetAchievementRecommendationsCurrentFocus `json:",omitempty,omitzero"`
}

func unpackGetAchievementRecommendationsParams(packed middleware.Parameters) (params GetAchievementRecommendationsParams) {
	{
		key := middleware.ParameterKey{
			Name: "character_id",
			In:   "query",
		}
		params.CharacterID = packed[key].(uuid.UUID)
	}
	{
		key := middleware.ParameterKey{
			Name: "current_focus",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.CurrentFocus = v.(OptGetAchievementRecommendationsCurrentFocus)
		}
	}
	return params
}

func decodeGetAchievementRecommendationsParams(args [0]string, argsEscaped bool, r *http.Request) (params GetAchievementRecommendationsParams, _ error) {
	q := uri.NewQueryDecoder(r.URL.Query())
	// Decode query: character_id.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "character_id",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToUUID(val)
				if err != nil {
					return err
				}

				params.CharacterID = c
				return nil
			}); err != nil {
				return err
			}
		} else {
			return err
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "character_id",
			In:   "query",
			Err:  err,
		}
	}
	// Decode query: current_focus.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "current_focus",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotCurrentFocusVal GetAchievementRecommendationsCurrentFocus
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToString(val)
					if err != nil {
						return err
					}

					paramsDotCurrentFocusVal = GetAchievementRecommendationsCurrentFocus(c)
					return nil
				}(); err != nil {
					return err
				}
				params.CurrentFocus.SetTo(paramsDotCurrentFocusVal)
				return nil
			}); err != nil {
				return err
			}
			if err := func() error {
				if value, ok := params.CurrentFocus.Get(); ok {
					if err := func() error {
						if err := value.Validate(); err != nil {
							return err
						}
						return nil
					}(); err != nil {
						return err
					}
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "current_focus",
			In:   "query",
			Err:  err,
		}
	}
	return params, nil
}
