// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"
	"net/http"
)

// ServerInterface defines all companion service endpoints
type ServerInterface interface {
	// Health check
	CompanionServiceHealthCheck(ctx context.Context) (CompanionServiceHealthCheckRes, error)

	// Companion types management
	GetCompanionTypes(ctx context.Context) (GetCompanionTypesRes, error)
	GetCompanionType(ctx context.Context, params GetCompanionTypeParams) (GetCompanionTypeRes, error)

	// Player companion management
	GetPlayerCompanions(ctx context.Context, params GetPlayerCompanionsParams) (GetPlayerCompanionsRes, error)
	GetCompanionDetails(ctx context.Context, params GetCompanionDetailsParams) (GetCompanionDetailsRes, error)

	// Companion lifecycle
	PurchaseCompanion(ctx context.Context, params PurchaseCompanionParams, req *PurchaseCompanionRequest) (PurchaseCompanionRes, error)
	SummonCompanion(ctx context.Context, params SummonCompanionParams) (SummonCompanionRes, error)
	RecallCompanion(ctx context.Context, params RecallCompanionParams) (RecallCompanionRes, error)

	// Companion customization
	RenameCompanion(ctx context.Context, params RenameCompanionParams, req *RenameCompanionRequest) (RenameCompanionRes, error)
	AddCompanionExperience(ctx context.Context, params AddCompanionExperienceParams, req *AddCompanionExperienceRequest) (AddCompanionExperienceRes, error)

	// Abilities
	UseCompanionAbility(ctx context.Context, params UseCompanionAbilityParams) (UseCompanionAbilityRes, error)

	// Leaderboards
	GetPrestigeLeaderboard(ctx context.Context, params GetPrestigeLeaderboardParams) (GetPrestigeLeaderboardRes, error)

	// Social features
	VisitCompanionApartment(ctx context.Context, params VisitCompanionApartmentParams) (VisitCompanionApartmentRes, error)
}

// Server implements HTTP server with routing
type Server struct {
	handler ServerInterface
}

// NewServer creates a new HTTP server
func NewServer(handler ServerInterface, securityHandler interface{}) *Server {
	return &Server{
		handler: handler,
	}
}

// ServeHTTP implements http.Handler
func (s *Server) ServeHTTP(w http.ResponseWriter, r *http.Request) {
	// This would normally be generated by ogen
	// For now, return a simple response
	w.WriteHeader(http.StatusNotImplemented)
	w.Write([]byte(`{"error": "API not fully implemented"}`))
}

// Error response types
type CompanionServiceHealthCheckBadRequest struct {
	Error Error `json:"error"`
}

type GetCompanionTypeBadRequest struct {
	Error Error `json:"error"`
}

type GetPlayerCompanionsBadRequest struct {
	Error Error `json:"error"`
}

type GetCompanionDetailsBadRequest struct {
	Error Error `json:"error"`
}

type PurchaseCompanionBadRequest struct {
	Error Error `json:"error"`
}

type SummonCompanionBadRequest struct {
	Error Error `json:"error"`
}

type RecallCompanionBadRequest struct {
	Error Error `json:"error"`
}

type RenameCompanionBadRequest struct {
	Error Error `json:"error"`
}

type AddCompanionExperienceBadRequest struct {
	Error Error `json:"error"`
}

type UseCompanionAbilityBadRequest struct {
	Error Error `json:"error"`
}

type VisitCompanionApartmentBadRequest struct {
	Error Error `json:"error"`
}
