/*
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.17.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.necpgame.gameplayservice.api;

import com.necpgame.gameplayservice.model.Error;
import com.necpgame.gameplayservice.model.GetLeagueTypes200Response;
import com.necpgame.gameplayservice.model.Leaderboard;
import com.necpgame.gameplayservice.model.League;
import com.necpgame.gameplayservice.model.LeaguePhase;
import com.necpgame.gameplayservice.model.LeagueRewards;
import com.necpgame.gameplayservice.model.LeagueTime;
import com.necpgame.gameplayservice.model.MetaProgress;
import org.springframework.lang.Nullable;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.media.ExampleObject;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", comments = "Generator version: 7.17.0")
@Validated
@Tag(name = "League", description = "Система лиг")
public interface MetaApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    String PATH_GET_CURRENT_LEAGUE = "/meta/league/current";
    /**
     * GET /meta/league/current : Получить текущую лигу
     * Возвращает информацию о текущей активной лиге. Включает параметры, фазу, игровое время, оставшееся время до сброса. 
     *
     * @return Текущая лига (status code 200)
     */
    @Operation(
        operationId = "getCurrentLeague",
        summary = "Получить текущую лигу",
        description = "Возвращает информацию о текущей активной лиге. Включает параметры, фазу, игровое время, оставшееся время до сброса. ",
        tags = { "League" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Текущая лига", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = League.class), examples = {
                    @ExampleObject(
                        name = "",
                        value = "{\"league_id\":\"league_12\",\"name\":\"League of Shadows #12\",\"start_date\":\"2025-09-01T00:00:00Z\",\"end_date\":\"2025-12-27T00:00:00Z\",\"current_phase\":\"rise\",\"game_time_current\":\"2045-06-15T12:00:00Z\",\"game_time_start\":\"2020-01-01T00:00:00Z\",\"game_time_end\":\"2093-07-27T00:00:00Z\",\"real_time_remaining\":\"2 месяца 15 дней\",\"time_acceleration\":20,\"league_type\":\"standard\"}"
                    )
                })

            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = MetaApi.PATH_GET_CURRENT_LEAGUE,
        produces = { "application/json" }
    )
    default ResponseEntity<League> getCurrentLeague(
        
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"end_date\" : \"2000-01-23T04:56:07.000+00:00\", \"real_time_remaining\" : \"real_time_remaining\", \"player_count\" : 0, \"game_time_current\" : \"2000-01-23T04:56:07.000+00:00\", \"league_type\" : \"standard\", \"current_phase\" : \"start\", \"name\" : \"League of Shadows #12\", \"time_acceleration\" : 20, \"game_time_start\" : \"2020-01-01T00:00:00Z\", \"league_id\" : \"league_12\", \"start_date\" : \"2000-01-23T04:56:07.000+00:00\", \"game_time_end\" : \"2093-07-27T00:00:00Z\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    String PATH_GET_CURRENT_PHASE = "/meta/league/phase";
    /**
     * GET /meta/league/phase : Получить текущую фазу лиги
     * Возвращает детали текущей фазы лиги (Start, Rise, Crisis, Endgame, Finale). Каждая фаза имеет свои особенности и контент. 
     *
     * @return Текущая фаза (status code 200)
     */
    @Operation(
        operationId = "getCurrentPhase",
        summary = "Получить текущую фазу лиги",
        description = "Возвращает детали текущей фазы лиги (Start, Rise, Crisis, Endgame, Finale). Каждая фаза имеет свои особенности и контент. ",
        tags = { "League" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Текущая фаза", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = LeaguePhase.class), examples = {
                    @ExampleObject(
                        name = "",
                        value = "{\"phase_name\":\"crisis\",\"era_range\":\"2060-2090\",\"focus\":\"Blackwall кризис, Пятая война, глобальные конфликты\",\"started_at\":\"2025-10-01T00:00:00Z\",\"ends_at\":\"2025-11-30T23:59:59Z\",\"active_events\":[\"Blackwall Crisis\",\"Fifth Corporate War\"],\"special_mechanics\":[\"Increased difficulty\",\"Global events frequency +50%\"]}"
                    )
                })

            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = MetaApi.PATH_GET_CURRENT_PHASE,
        produces = { "application/json" }
    )
    default ResponseEntity<LeaguePhase> getCurrentPhase(
        
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"era_range\" : \"2060-2090\", \"active_events\" : [ \"active_events\", \"active_events\" ], \"focus\" : \"focus\", \"started_at\" : \"2000-01-23T04:56:07.000+00:00\", \"phase_name\" : \"start\", \"ends_at\" : \"2000-01-23T04:56:07.000+00:00\", \"special_mechanics\" : [ \"special_mechanics\", \"special_mechanics\" ] }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    String PATH_GET_LEAGUE_LEADERBOARD = "/meta/league/leaderboard";
    /**
     * GET /meta/league/leaderboard : Получить рейтинг лиги
     * Возвращает рейтинг игроков в текущей лиге. Можно фильтровать по типу (overall, pvp, pve, wealth, faction). 
     *
     * @param rankingType Тип рейтинга (optional, default to overall)
     * @param limit Количество записей (optional, default to 100)
     * @param offset Смещение (пагинация) (optional, default to 0)
     * @return Рейтинг (status code 200)
     */
    @Operation(
        operationId = "getLeagueLeaderboard",
        summary = "Получить рейтинг лиги",
        description = "Возвращает рейтинг игроков в текущей лиге. Можно фильтровать по типу (overall, pvp, pve, wealth, faction). ",
        tags = { "Rankings" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Рейтинг", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Leaderboard.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = MetaApi.PATH_GET_LEAGUE_LEADERBOARD,
        produces = { "application/json" }
    )
    default ResponseEntity<Leaderboard> getLeagueLeaderboard(
        @Parameter(name = "ranking_type", description = "Тип рейтинга", in = ParameterIn.QUERY) @Valid @RequestParam(value = "ranking_type", required = false, defaultValue = "overall") String rankingType,
        @Min(value = 1) @Max(value = 1000) @Parameter(name = "limit", description = "Количество записей", in = ParameterIn.QUERY) @Valid @RequestParam(value = "limit", required = false, defaultValue = "100") Integer limit,
        @Min(value = 0) @Parameter(name = "offset", description = "Смещение (пагинация)", in = ParameterIn.QUERY) @Valid @RequestParam(value = "offset", required = false, defaultValue = "0") Integer offset
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"rankings\" : [ { \"score\" : 6.027456183070403, \"account_id\" : \"account_id\", \"level\" : 1, \"character_name\" : \"character_name\", \"rank\" : 0, \"class\" : \"class\" }, { \"score\" : 6.027456183070403, \"account_id\" : \"account_id\", \"level\" : 1, \"character_name\" : \"character_name\", \"rank\" : 0, \"class\" : \"class\" } ], \"ranking_type\" : \"overall\", \"total_players\" : 5 }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    String PATH_GET_LEAGUE_REWARDS = "/meta/league/rewards";
    /**
     * GET /meta/league/rewards : Получить награды лиги
     * Возвращает награды за текущую лигу (по рейтингу). Награды выдаются в конце лиги (Finale). 
     *
     * @param accountId  (required)
     * @return Доступные награды (status code 200)
     */
    @Operation(
        operationId = "getLeagueRewards",
        summary = "Получить награды лиги",
        description = "Возвращает награды за текущую лигу (по рейтингу). Награды выдаются в конце лиги (Finale). ",
        tags = { "League" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Доступные награды", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = LeagueRewards.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = MetaApi.PATH_GET_LEAGUE_REWARDS,
        produces = { "application/json" }
    )
    default ResponseEntity<LeagueRewards> getLeagueRewards(
        @NotNull @Parameter(name = "account_id", description = "", required = true, in = ParameterIn.QUERY) @Valid @RequestParam(value = "account_id", required = true) String accountId
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"account_id\" : \"account_id\", \"current_rank\" : 0, \"rewards\" : [ { \"reward_type\" : \"title\", \"name\" : \"name\", \"reward_id\" : \"reward_id\", \"requirement\" : \"requirement\" }, { \"reward_type\" : \"title\", \"name\" : \"name\", \"reward_id\" : \"reward_id\", \"requirement\" : \"requirement\" } ] }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    String PATH_GET_LEAGUE_TIME = "/meta/league/time";
    /**
     * GET /meta/league/time : Получить игровое время
     * Возвращает текущее игровое время в лиге и параметры ускорения. Игровое время: 2020-2093 (73 года). 
     *
     * @return Игровое время (status code 200)
     */
    @Operation(
        operationId = "getLeagueTime",
        summary = "Получить игровое время",
        description = "Возвращает текущее игровое время в лиге и параметры ускорения. Игровое время: 2020-2093 (73 года). ",
        tags = { "League" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Игровое время", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = LeagueTime.class), examples = {
                    @ExampleObject(
                        name = "",
                        value = "{\"game_time\":\"2055-03-20T14:30:00Z\",\"real_time\":\"2025-10-15T18:45:00Z\",\"time_acceleration\":20,\"days_passed_game\":12861,\"days_remaining_game\":13973,\"era\":\"2045-2060\"}"
                    )
                })

            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = MetaApi.PATH_GET_LEAGUE_TIME,
        produces = { "application/json" }
    )
    default ResponseEntity<LeagueTime> getLeagueTime(
        
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"days_remaining_game\" : 1, \"era\" : \"2045-2060\", \"game_time\" : \"2000-01-23T04:56:07.000+00:00\", \"real_time\" : \"2000-01-23T04:56:07.000+00:00\", \"time_acceleration\" : 0.8008281904610115, \"days_passed_game\" : 6 }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    String PATH_GET_LEAGUE_TYPES = "/meta/league/types";
    /**
     * GET /meta/league/types : Получить типы лиг
     * Возвращает доступные типы лиг (Standard, Hardcore, Event). Игрок выбирает тип при создании персонажа. 
     *
     * @return Типы лиг (status code 200)
     */
    @Operation(
        operationId = "getLeagueTypes",
        summary = "Получить типы лиг",
        description = "Возвращает доступные типы лиг (Standard, Hardcore, Event). Игрок выбирает тип при создании персонажа. ",
        tags = { "League" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Типы лиг", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = GetLeagueTypes200Response.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = MetaApi.PATH_GET_LEAGUE_TYPES,
        produces = { "application/json" }
    )
    default ResponseEntity<GetLeagueTypes200Response> getLeagueTypes(
        
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"league_types\" : [ { \"special_rules\" : [ \"Permadeath on character death\", \"No trading with other players\" ], \"type_id\" : \"standard\", \"name\" : \"name\", \"wipe_rules\" : { \"wipes_characters\" : true, \"wipes_items\" : true, \"wipes_reputation\" : true }, \"description\" : \"description\" }, { \"special_rules\" : [ \"Permadeath on character death\", \"No trading with other players\" ], \"type_id\" : \"standard\", \"name\" : \"name\", \"wipe_rules\" : { \"wipes_characters\" : true, \"wipes_items\" : true, \"wipes_reputation\" : true }, \"description\" : \"description\" } ] }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    String PATH_GET_META_PROGRESS = "/meta/league/meta-progress/{account_id}";
    /**
     * GET /meta/league/meta-progress/{account_id} : Получить мета-прогресс аккаунта
     * Возвращает мета-прогресс аккаунта (сохраняется между лигами). Включает: рейтинг, достижения, титулы, косметику. 
     *
     * @param accountId ID аккаунта (required)
     * @return Мета-прогресс (status code 200)
     *         or Запрошенный ресурс не найден.  (status code 404)
     */
    @Operation(
        operationId = "getMetaProgress",
        summary = "Получить мета-прогресс аккаунта",
        description = "Возвращает мета-прогресс аккаунта (сохраняется между лигами). Включает: рейтинг, достижения, титулы, косметику. ",
        tags = { "Meta Progress" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Мета-прогресс", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = MetaProgress.class))
            }),
            @ApiResponse(responseCode = "404", description = "Запрошенный ресурс не найден. ", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class), examples = {
                    @ExampleObject(
                        name = "",
                        value = "{\"error\":{\"code\":\"NOT_FOUND\",\"message\":\"Запрошенный ресурс не найден\",\"details\":[{\"field\":\"id\",\"message\":\"NPC с указанным ID не существует\",\"code\":\"RESOURCE_NOT_FOUND\"}]}}"
                    )
                })

            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = MetaApi.PATH_GET_META_PROGRESS,
        produces = { "application/json" }
    )
    default ResponseEntity<MetaProgress> getMetaProgress(
        @NotNull @Parameter(name = "account_id", description = "ID аккаунта", required = true, in = ParameterIn.PATH) @PathVariable("account_id") String accountId
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"account_id\" : \"account_id\", \"achievements\" : [ { \"achievement_id\" : \"achievement_id\", \"name\" : \"name\", \"earned_in_league\" : \"earned_in_league\" }, { \"achievement_id\" : \"achievement_id\", \"name\" : \"name\", \"earned_in_league\" : \"earned_in_league\" } ], \"global_rating\" : { \"mmr\" : 0.8008281904610115, \"elo\" : 6.027456183070403, \"rank\" : \"rank\" }, \"titles\" : [ { \"league_earned\" : \"league_earned\", \"title_id\" : \"title_id\", \"name\" : \"name\" }, { \"league_earned\" : \"league_earned\", \"title_id\" : \"title_id\", \"name\" : \"name\" } ], \"hall_of_fame\" : [ { \"rank\" : 1, \"category\" : \"category\", \"league_id\" : \"league_id\" }, { \"rank\" : 1, \"category\" : \"category\", \"league_id\" : \"league_id\" } ], \"legacy_items\" : [ { \"league_source\" : \"league_source\", \"item_id\" : \"item_id\" }, { \"league_source\" : \"league_source\", \"item_id\" : \"item_id\" } ], \"cosmetics\" : [ \"cosmetics\", \"cosmetics\" ] }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"error\" : { \"code\" : \"VALIDATION_ERROR\", \"details\" : [ { \"code\" : \"code\", \"field\" : \"field\", \"message\" : \"message\" }, { \"code\" : \"code\", \"field\" : \"field\", \"message\" : \"message\" } ], \"message\" : \"Неверные параметры запроса\" } }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }

}
