// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// GetDashboard implements getDashboard operation.
//
// Главная панель администрирования.
//
// GET /dashboard
func (UnimplementedHandler) GetDashboard(ctx context.Context) (r GetDashboardRes, _ error) {
	return r, ht.ErrNotImplemented
}
