// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package api

import (
	"context"
	"fmt"
	"net/http"

	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes = "BearerAuth.Scopes"
)

// Defines values for CurrentTurnAvailableActions.
const (
	Ability CurrentTurnAvailableActions = "ability"
	Attack  CurrentTurnAvailableActions = "attack"
	Defend  CurrentTurnAvailableActions = "defend"
	Item    CurrentTurnAvailableActions = "item"
	Move    CurrentTurnAvailableActions = "move"
	Skip    CurrentTurnAvailableActions = "skip"
)

// Defines values for CurrentTurnCombatPhase.
const (
	Active      CurrentTurnCombatPhase = "active"
	Completion  CurrentTurnCombatPhase = "completion"
	Preparation CurrentTurnCombatPhase = "preparation"
)

// Defines values for SkipTurnJSONBodyReason.
const (
	Disconnected SkipTurnJSONBodyReason = "disconnected"
	Manual       SkipTurnJSONBodyReason = "manual"
	StatusEffect SkipTurnJSONBodyReason = "status_effect"
	Timeout      SkipTurnJSONBodyReason = "timeout"
)

// CurrentTurn defines model for CurrentTurn.
type CurrentTurn struct {
	// AvailableActions Список доступных действий для текущего участника
	AvailableActions *[]CurrentTurnAvailableActions `json:"available_actions,omitempty"`

	// CombatPhase Фаза боя:
	// - `preparation` - подготовка, расстановка участников
	// - `active` - активный бой
	// - `completion` - завершение, подсчёт наград
	CombatPhase *CurrentTurnCombatPhase `json:"combat_phase,omitempty"`

	// CurrentParticipant ID участника чей ход
	CurrentParticipant *openapi_types.UUID `json:"current_participant,omitempty"`

	// SessionId ID боевой сессии
	SessionId *openapi_types.UUID `json:"session_id,omitempty"`

	// TimeRemaining Оставшееся время в секундах до таймаута
	TimeRemaining *int `json:"time_remaining,omitempty"`

	// TurnNumber Номер текущего хода (начинается с 1)
	TurnNumber *int `json:"turn_number,omitempty"`
}

// CurrentTurnAvailableActions defines model for CurrentTurn.AvailableActions.
type CurrentTurnAvailableActions string

// CurrentTurnCombatPhase Фаза боя:
// - `preparation` - подготовка, расстановка участников
// - `active` - активный бой
// - `completion` - завершение, подсчёт наград
type CurrentTurnCombatPhase string

// Error defines model for Error.
type Error struct {
	// Code Код ошибки
	Code *string `json:"code"`

	// Details Дополнительные детали ошибки
	Details *map[string]interface{} `json:"details"`

	// Error Тип ошибки
	Error string `json:"error"`

	// Message Сообщение об ошибке
	Message string `json:"message"`
}

// SessionId defines model for SessionId.
type SessionId = openapi_types.UUID

// BadRequest defines model for BadRequest.
type BadRequest = Error

// NotFound defines model for NotFound.
type NotFound = Error

// Unauthorized defines model for Unauthorized.
type Unauthorized = Error

// SkipTurnJSONBody defines parameters for SkipTurn.
type SkipTurnJSONBody struct {
	// Reason Причина пропуска хода
	Reason *SkipTurnJSONBodyReason `json:"reason,omitempty"`
}

// SkipTurnJSONBodyReason defines parameters for SkipTurn.
type SkipTurnJSONBodyReason string

// SkipTurnJSONRequestBody defines body for SkipTurn for application/json ContentType.
type SkipTurnJSONRequestBody SkipTurnJSONBody

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Текущий ход
	// (GET /api/v1/gameplay/combat/sessions/{session_id}/current-turn)
	GetCurrentTurn(w http.ResponseWriter, r *http.Request, sessionId SessionId)
	// Следующий ход
	// (POST /api/v1/gameplay/combat/sessions/{session_id}/next-turn)
	NextTurn(w http.ResponseWriter, r *http.Request, sessionId SessionId)
	// Пропуск хода
	// (POST /api/v1/gameplay/combat/sessions/{session_id}/skip-turn)
	SkipTurn(w http.ResponseWriter, r *http.Request, sessionId SessionId)
	// Порядок ходов
	// (GET /api/v1/gameplay/combat/sessions/{session_id}/turn-order)
	GetTurnOrder(w http.ResponseWriter, r *http.Request, sessionId SessionId)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Текущий ход
// (GET /api/v1/gameplay/combat/sessions/{session_id}/current-turn)
func (_ Unimplemented) GetCurrentTurn(w http.ResponseWriter, r *http.Request, sessionId SessionId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Следующий ход
// (POST /api/v1/gameplay/combat/sessions/{session_id}/next-turn)
func (_ Unimplemented) NextTurn(w http.ResponseWriter, r *http.Request, sessionId SessionId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Пропуск хода
// (POST /api/v1/gameplay/combat/sessions/{session_id}/skip-turn)
func (_ Unimplemented) SkipTurn(w http.ResponseWriter, r *http.Request, sessionId SessionId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Порядок ходов
// (GET /api/v1/gameplay/combat/sessions/{session_id}/turn-order)
func (_ Unimplemented) GetTurnOrder(w http.ResponseWriter, r *http.Request, sessionId SessionId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetCurrentTurn operation middleware
func (siw *ServerInterfaceWrapper) GetCurrentTurn(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "session_id" -------------
	var sessionId SessionId

	err = runtime.BindStyledParameterWithOptions("simple", "session_id", chi.URLParam(r, "session_id"), &sessionId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "session_id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetCurrentTurn(w, r, sessionId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// NextTurn operation middleware
func (siw *ServerInterfaceWrapper) NextTurn(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "session_id" -------------
	var sessionId SessionId

	err = runtime.BindStyledParameterWithOptions("simple", "session_id", chi.URLParam(r, "session_id"), &sessionId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "session_id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.NextTurn(w, r, sessionId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SkipTurn operation middleware
func (siw *ServerInterfaceWrapper) SkipTurn(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "session_id" -------------
	var sessionId SessionId

	err = runtime.BindStyledParameterWithOptions("simple", "session_id", chi.URLParam(r, "session_id"), &sessionId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "session_id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SkipTurn(w, r, sessionId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetTurnOrder operation middleware
func (siw *ServerInterfaceWrapper) GetTurnOrder(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "session_id" -------------
	var sessionId SessionId

	err = runtime.BindStyledParameterWithOptions("simple", "session_id", chi.URLParam(r, "session_id"), &sessionId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "session_id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetTurnOrder(w, r, sessionId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/gameplay/combat/sessions/{session_id}/current-turn", wrapper.GetCurrentTurn)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/gameplay/combat/sessions/{session_id}/next-turn", wrapper.NextTurn)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/gameplay/combat/sessions/{session_id}/skip-turn", wrapper.SkipTurn)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/gameplay/combat/sessions/{session_id}/turn-order", wrapper.GetTurnOrder)
	})

	return r
}
