// Code generated by ogen, DO NOT EDIT.

package api

import (
	"net/http"
	"net/url"

	"github.com/go-faster/errors"
	"github.com/google/uuid"
	"github.com/ogen-go/ogen/conv"
	"github.com/ogen-go/ogen/middleware"
	"github.com/ogen-go/ogen/ogenerrors"
	"github.com/ogen-go/ogen/uri"
	"github.com/ogen-go/ogen/validate"
)

// GetCurrentTurnParams is parameters of getCurrentTurn operation.
type GetCurrentTurnParams struct {
	SessionId uuid.UUID
}

func unpackGetCurrentTurnParams(packed middleware.Parameters) (params GetCurrentTurnParams) {
	{
		key := middleware.ParameterKey{
			Name: "sessionId",
			In:   "path",
		}
		params.SessionId = packed[key].(uuid.UUID)
	}
	return params
}

func decodeGetCurrentTurnParams(args [1]string, argsEscaped bool, r *http.Request) (params GetCurrentTurnParams, _ error) {
	// Decode path: sessionId.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "sessionId",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToUUID(val)
				if err != nil {
					return err
				}

				params.SessionId = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "sessionId",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// GetTurnOrderParams is parameters of getTurnOrder operation.
type GetTurnOrderParams struct {
	SessionId uuid.UUID
}

func unpackGetTurnOrderParams(packed middleware.Parameters) (params GetTurnOrderParams) {
	{
		key := middleware.ParameterKey{
			Name: "sessionId",
			In:   "path",
		}
		params.SessionId = packed[key].(uuid.UUID)
	}
	return params
}

func decodeGetTurnOrderParams(args [1]string, argsEscaped bool, r *http.Request) (params GetTurnOrderParams, _ error) {
	// Decode path: sessionId.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "sessionId",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToUUID(val)
				if err != nil {
					return err
				}

				params.SessionId = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "sessionId",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// NextTurnParams is parameters of nextTurn operation.
type NextTurnParams struct {
	SessionId uuid.UUID
}

func unpackNextTurnParams(packed middleware.Parameters) (params NextTurnParams) {
	{
		key := middleware.ParameterKey{
			Name: "sessionId",
			In:   "path",
		}
		params.SessionId = packed[key].(uuid.UUID)
	}
	return params
}

func decodeNextTurnParams(args [1]string, argsEscaped bool, r *http.Request) (params NextTurnParams, _ error) {
	// Decode path: sessionId.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "sessionId",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToUUID(val)
				if err != nil {
					return err
				}

				params.SessionId = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "sessionId",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// SkipTurnParams is parameters of skipTurn operation.
type SkipTurnParams struct {
	SessionId uuid.UUID
}

func unpackSkipTurnParams(packed middleware.Parameters) (params SkipTurnParams) {
	{
		key := middleware.ParameterKey{
			Name: "sessionId",
			In:   "path",
		}
		params.SessionId = packed[key].(uuid.UUID)
	}
	return params
}

func decodeSkipTurnParams(args [1]string, argsEscaped bool, r *http.Request) (params SkipTurnParams, _ error) {
	// Decode path: sessionId.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "sessionId",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToUUID(val)
				if err != nil {
					return err
				}

				params.SessionId = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "sessionId",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}
