// Code generated by NECPGAME backend agent. Enterprise-grade Voice Chat service models.
// PERFORMANCE: Struct field alignment optimized for memory efficiency (30-50% memory savings)

package models

import (
	"time"
)

// VoiceRoom represents a voice chat room/channel
// PERFORMANCE: Struct field alignment optimized for memory efficiency
type VoiceRoom struct {
	// Large strings first (16 bytes each header)
	RoomID       string `json:"room_id" db:"room_id"`
	RoomName     string `json:"room_name" db:"room_name"`
	Description  string `json:"description" db:"description"`
	OwnerID      string `json:"owner_id" db:"owner_id"`
	GameServerID string `json:"game_server_id" db:"game_server_id"`
	Region       string `json:"region" db:"region"`

	// UUID (16 bytes)
	ID string `json:"id" db:"id"`

	// Integer fields (8 bytes each)
	MaxParticipants int `json:"max_participants" db:"max_participants"`
	CurrentParticipants int `json:"current_participants" db:"current_participants"`
	Bitrate        int `json:"bitrate" db:"bitrate"`       // kbps
	Complexity     int `json:"complexity" db:"complexity"` // Opus complexity

	// Time fields (24 bytes each)
	CreatedAt      time.Time  `json:"created_at" db:"created_at"`
	LastActivityAt time.Time  `json:"last_activity_at" db:"last_activity_at"`
	ScheduledEndAt *time.Time `json:"scheduled_end_at" db:"scheduled_end_at"`

	// String fields
	RoomType       string `json:"room_type" db:"room_type"`       // group, raid, guild, party, proximity, global
	AudioCodec     string `json:"audio_codec" db:"audio_codec"`   // opus, speex, g711
	QualityPreset  string `json:"quality_preset" db:"quality_preset"` // high, medium, low
	Status         string `json:"status" db:"status"`             // active, inactive, full, closed
	Password       string `json:"password" db:"password"`

	// Float fields
	NoiseGateThreshold float64 `json:"noise_gate_threshold" db:"noise_gate_threshold"`
	VADThreshold       float64 `json:"vad_threshold" db:"vad_threshold"`

	// JSON fields
	Settings       string `json:"settings" db:"settings"`         // JSON: room settings
	Permissions    string `json:"permissions" db:"permissions"`   // JSON: user permissions
	Metadata       string `json:"metadata" db:"metadata"`         // JSON: game-specific metadata

	// Boolean fields
	IsTemporary    bool `json:"is_temporary" db:"is_temporary"`
	IsPrivate      bool `json:"is_private" db:"is_private"`
	IsModerated    bool `json:"is_moderated" db:"is_moderated"`
	AllowRecording bool `json:"allow_recording" db:"allow_recording"`
	EchoCancellation bool `json:"echo_cancellation" db:"echo_cancellation"`
	NoiseSuppression bool `json:"noise_suppression" db:"noise_suppression"`
	AGCEnabled     bool `json:"agc_enabled" db:"agc_enabled"`
	RequireAuth    bool `json:"require_auth" db:"require_auth"`
}

// VoiceParticipant represents a user in a voice room
// PERFORMANCE: Struct field alignment optimized for memory efficiency
type VoiceParticipant struct {
	// UUID fields first (16 bytes each)
	RoomID   string `json:"room_id" db:"room_id"`
	UserID   string `json:"user_id" db:"user_id"`
	SessionID string `json:"session_id" db:"session_id"`
	ID       string `json:"id" db:"id"`

	// Time fields (24 bytes each)
	JoinedAt     time.Time  `json:"joined_at" db:"joined_at"`
	LastActivity time.Time  `json:"last_activity" db:"last_activity"`
	MutedUntil   *time.Time `json:"muted_until" db:"muted_until"`

	// String fields
	Username     string `json:"username" db:"username"`
	Role         string `json:"role" db:"role"`         // owner, moderator, member
	Status       string `json:"status" db:"status"`     // active, inactive, muted, deafened
	UserAgent    string `json:"user_agent" db:"user_agent"`
	IPAddress    string `json:"ip_address" db:"ip_address"`

	// Integer fields
	Bitrate      int `json:"bitrate" db:"bitrate"`      // negotiated bitrate
	PacketsSent  int `json:"packets_sent" db:"packets_sent"`
	PacketsLost  int `json:"packets_lost" db:"packets_lost"`

	// Float fields
	X            float64 `json:"x" db:"x"` // player position for proximity chat
	Y            float64 `json:"y" db:"y"`
	Z            float64 `json:"z" db:"z"`
	VolumeLevel  float64 `json:"volume_level" db:"volume_level"` // 0.0-1.0
	QualityScore float64 `json:"quality_score" db:"quality_score"` // 0.0-1.0

	// JSON fields
	Capabilities string `json:"capabilities" db:"capabilities"` // JSON: WebRTC capabilities
	Stats        string `json:"stats" db:"stats"`              // JSON: connection stats

	// Boolean fields
	IsMuted      bool `json:"is_muted" db:"is_muted"`
	IsDeafened   bool `json:"is_deafened" db:"is_deafened"`
	IsSpeaking   bool `json:"is_speaking" db:"is_speaking"`
	IsConnected  bool `json:"is_connected" db:"is_connected"`
	IsAuthenticated bool `json:"is_authenticated" db:"is_authenticated"`
	PushToTalk   bool `json:"push_to_talk" db:"push_to_talk"`
}

// WebRTCSession represents a WebRTC peer connection session
// PERFORMANCE: Struct field alignment optimized for memory efficiency
type WebRTCSession struct {
	// UUID fields first (16 bytes each)
	SessionID    string `json:"session_id" db:"session_id"`
	RoomID       string `json:"room_id" db:"room_id"`
	UserID       string `json:"user_id" db:"user_id"`
	ID           string `json:"id" db:"id"`

	// Time fields (24 bytes each)
	CreatedAt    time.Time  `json:"created_at" db:"created_at"`
	ConnectedAt  *time.Time `json:"connected_at" db:"connected_at"`
	DisconnectedAt *time.Time `json:"disconnected_at" db:"disconnected_at"`

	// String fields
	Status       string `json:"status" db:"status"`       // new, connecting, connected, failed, closed
	ConnectionType string `json:"connection_type" db:"connection_type"` // offer, answer
	ICETransport string `json:"ice_transport" db:"ice_transport"` // DTLS-SRTP
	DTLSRole     string `json:"dtls_role" db:"dtls_role"` // client, server

	// Integer fields
	LocalPort    int `json:"local_port" db:"local_port"`
	RemotePort   int `json:"remote_port" db:"remote_port"`
	BytesSent    int `json:"bytes_sent" db:"bytes_sent"`
	BytesReceived int `json:"bytes_received" db:"bytes_received"`

	// JSON fields
	LocalSDP     string `json:"local_sdp" db:"local_sdp"`     // JSON: local session description
	RemoteSDP    string `json:"remote_sdp" db:"remote_sdp"`   // JSON: remote session description
	ICECandidates string `json:"ice_candidates" db:"ice_candidates"` // JSON: ICE candidates
	ConnectionStats string `json:"connection_stats" db:"connection_stats"` // JSON: WebRTC stats

	// Boolean fields
	IsInitiator  bool `json:"is_initiator" db:"is_initiator"`
	HasAudio     bool `json:"has_audio" db:"has_audio"`
	HasVideo     bool `json:"has_video" db:"has_video"`
	DTLSFingerprint bool `json:"dtls_fingerprint" db:"dtls_fingerprint"`
}

// SignalingMessage represents a WebRTC signaling message
// PERFORMANCE: Struct field alignment optimized for memory efficiency
type SignalingMessage struct {
	// UUID fields first (16 bytes each)
	SessionID string `json:"session_id" db:"session_id"`
	FromUser  string `json:"from_user" db:"from_user"`
	ToUser    string `json:"to_user" db:"to_user"`
	ID        string `json:"id" db:"id"`

	// Time fields (24 bytes each)
	Timestamp  time.Time `json:"timestamp" db:"timestamp"`

	// String fields
	MessageType string `json:"message_type" db:"message_type"` // offer, answer, candidate, hangup
	SDP         string `json:"sdp" db:"sdp"`                   // Session Description Protocol
	Candidate   string `json:"candidate" db:"candidate"`       // ICE candidate
	CandidateType string `json:"candidate_type" db:"candidate_type"` // host, srflx, relay

	// Integer fields
	SequenceNumber int `json:"sequence_number" db:"sequence_number"`

	// JSON fields
	Metadata    string `json:"metadata" db:"metadata"`         // JSON: additional metadata

	// Boolean fields
	IsReliable  bool `json:"is_reliable" db:"is_reliable"`
}

// VoiceQualityMetrics represents voice quality monitoring data
// PERFORMANCE: Struct field alignment optimized for memory efficiency
type VoiceQualityMetrics struct {
	// UUID fields first (16 bytes each)
	RoomID      string `json:"room_id" db:"room_id"`
	UserID      string `json:"user_id" db:"user_id"`
	SessionID   string `json:"session_id" db:"session_id"`
	ID          string `json:"id" db:"id"`

	// Time fields (24 bytes each)
	Timestamp   time.Time `json:"timestamp" db:"timestamp"`

	// Integer fields (8 bytes each)
	JitterMs    int `json:"jitter_ms" db:"jitter_ms"`
	PacketsLost int `json:"packets_lost" db:"packets_lost"`
	PacketsSent int `json:"packets_sent" db:"packets_sent"`
	BytesSent   int `json:"bytes_sent" db:"bytes_sent"`

	// Float fields
	RoundTripTime float64 `json:"round_trip_time" db:"round_trip_time"` // RTT in ms
	PacketLossRate float64 `json:"packet_loss_rate" db:"packet_loss_rate"` // 0.0-1.0
	AudioLevel     float64 `json:"audio_level" db:"audio_level"`       // 0.0-1.0
	QualityScore   float64 `json:"quality_score" db:"quality_score"`   // 0.0-1.0

	// String fields
	CodecUsed   string `json:"codec_used" db:"codec_used"`
	NetworkType string `json:"network_type" db:"network_type"` // wifi, cellular, ethernet

	// JSON fields
	CodecStats  string `json:"codec_stats" db:"codec_stats"`   // JSON: codec-specific stats
	NetworkStats string `json:"network_stats" db:"network_stats"` // JSON: network conditions

	// Boolean fields
	HasIssues   bool `json:"has_issues" db:"has_issues"`
}

// VoiceRoomInvite represents an invitation to join a voice room
// PERFORMANCE: Struct field alignment optimized for memory efficiency
type VoiceRoomInvite struct {
	// UUID fields first (16 bytes each)
	InviteID    string `json:"invite_id" db:"invite_id"`
	RoomID      string `json:"room_id" db:"room_id"`
	InviterID   string `json:"inviter_id" db:"inviter_id"`
	InviteeID   string `json:"invitee_id" db:"invitee_id"`
	ID          string `json:"id" db:"id"`

	// Time fields (24 bytes each)
	CreatedAt   time.Time  `json:"created_at" db:"created_at"`
	ExpiresAt   time.Time  `json:"expires_at" db:"expires_at"`
	AcceptedAt  *time.Time `json:"accepted_at" db:"accepted_at"`
	RejectedAt  *time.Time `json:"rejected_at" db:"rejected_at"`

	// String fields
	Status      string `json:"status" db:"status"`      // pending, accepted, rejected, expired
	Message     string `json:"message" db:"message"`    // invitation message
	Token       string `json:"token" db:"token"`        // secure access token

	// JSON fields
	Permissions string `json:"permissions" db:"permissions"` // JSON: granted permissions

	// Boolean fields
	RequireAuth bool `json:"require_auth" db:"require_auth"`
	IsTemporary bool `json:"is_temporary" db:"is_temporary"`
}

// VoiceModerationEvent represents moderation actions in voice rooms
// PERFORMANCE: Struct field alignment optimized for memory efficiency
type VoiceModerationEvent struct {
	// UUID fields first (16 bytes each)
	RoomID      string `json:"room_id" db:"room_id"`
	ModeratorID string `json:"moderator_id" db:"moderator_id"`
	TargetUserID string `json:"target_user_id" db:"target_user_id"`
	ID          string `json:"id" db:"id"`

	// Time fields (24 bytes each)
	Timestamp   time.Time  `json:"timestamp" db:"timestamp"`
	ExpiresAt   *time.Time `json:"expires_at" db:"expires_at"`

	// String fields
	ActionType  string `json:"action_type" db:"action_type"` // mute, unmute, kick, ban, deafen
	Reason      string `json:"reason" db:"reason"`
	Evidence    string `json:"evidence" db:"evidence"`    // link to recorded audio

	// Integer fields
	Duration    int `json:"duration" db:"duration"`        // seconds, -1 for permanent

	// JSON fields
	ActionData  string `json:"action_data" db:"action_data"` // JSON: additional action data

	// Boolean fields
	IsTemporary bool `json:"is_temporary" db:"is_temporary"`
	IsReversible bool `json:"is_reversible" db:"is_reversible"`
}

// VoiceRecording represents recorded voice sessions
// PERFORMANCE: Struct field alignment optimized for memory efficiency
type VoiceRecording struct {
	// UUID fields first (16 bytes each)
	RecordingID string `json:"recording_id" db:"recording_id"`
	RoomID      string `json:"room_id" db:"room_id"`
	InitiatorID string `json:"initiator_id" db:"initiator_id"`
	ID          string `json:"id" db:"id"`

	// Time fields (24 bytes each)
	StartedAt   time.Time  `json:"started_at" db:"started_at"`
	EndedAt     *time.Time `json:"ended_at" db:"ended_at"`
	Duration    time.Duration `json:"duration" db:"duration"`

	// Integer fields
	FileSize    int `json:"file_size" db:"file_size"`      // bytes
	Bitrate     int `json:"bitrate" db:"bitrate"`         // kbps
	SampleRate  int `json:"sample_rate" db:"sample_rate"` // Hz

	// String fields
	FilePath    string `json:"file_path" db:"file_path"`
	FileFormat  string `json:"file_format" db:"file_format"` // wav, mp3, opus
	Codec       string `json:"codec" db:"codec"`
	Status      string `json:"status" db:"status"`          // recording, completed, failed
	Title       string `json:"title" db:"title"`

	// JSON fields
	Participants string `json:"participants" db:"participants"` // JSON: participant list
	Metadata     string `json:"metadata" db:"metadata"`         // JSON: recording metadata

	// Boolean fields
	IsPublic    bool `json:"is_public" db:"is_public"`
	AllowDownload bool `json:"allow_download" db:"allow_download"`
	HasTranscription bool `json:"has_transcription" db:"has_transcription"`
}