/*
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.17.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.necpgame.backjava.api;

import com.necpgame.backjava.model.EconomicMultipliers;
import com.necpgame.backjava.model.Error;
import com.necpgame.backjava.model.GetActiveWorldEvents200Response;
import com.necpgame.backjava.model.GetCharacterAffectedEvents200Response;
import org.springframework.lang.Nullable;
import java.util.UUID;
import com.necpgame.backjava.model.WorldEventDetailed;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.media.ExampleObject;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", comments = "Generator version: 7.17.0")
@Validated
@Tag(name = "World Events", description = "Мировые события")
public interface WorldEventsApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    String PATH_GET_ACTIVE_WORLD_EVENTS = "/gameplay/world/events";
    /**
     * GET /gameplay/world/events : Получить активные мировые события
     *
     * @param era  (optional)
     * @param eventType  (optional)
     * @param page Номер страницы (начинается с 1) (optional, default to 1)
     * @param pageSize Количество элементов на странице (optional, default to 20)
     * @return Активные события (status code 200)
     */
    @Operation(
        operationId = "getActiveWorldEvents",
        summary = "Получить активные мировые события",
        tags = { "World Events" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Активные события", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = GetActiveWorldEvents200Response.class))
            })
        },
        security = {
            @SecurityRequirement(name = "BearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = WorldEventsApi.PATH_GET_ACTIVE_WORLD_EVENTS,
        produces = { "application/json" }
    )
    default ResponseEntity<GetActiveWorldEvents200Response> getActiveWorldEvents(
        @Parameter(name = "era", description = "", in = ParameterIn.QUERY) @Valid @RequestParam(value = "era", required = false) @Nullable String era,
        @Parameter(name = "event_type", description = "", in = ParameterIn.QUERY) @Valid @RequestParam(value = "event_type", required = false) @Nullable String eventType,
        @Min(value = 1) @Parameter(name = "page", description = "Номер страницы (начинается с 1)", in = ParameterIn.QUERY) @Valid @RequestParam(value = "page", required = false, defaultValue = "1") Integer page,
        @Min(value = 1) @Max(value = 100) @Parameter(name = "page_size", description = "Количество элементов на странице", in = ParameterIn.QUERY) @Valid @RequestParam(value = "page_size", required = false, defaultValue = "20") Integer pageSize
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"data\" : [ { \"severity\" : \"MINOR\", \"end_date\" : \"2000-01-23T04:56:07.000+00:00\", \"affected_regions\" : [ \"affected_regions\", \"affected_regions\" ], \"event_id\" : \"event_id\", \"is_active\" : true, \"era\" : \"era\", \"name\" : \"The DataKrash (2020)\", \"type\" : \"GLOBAL\", \"start_date\" : \"2000-01-23T04:56:07.000+00:00\" }, { \"severity\" : \"MINOR\", \"end_date\" : \"2000-01-23T04:56:07.000+00:00\", \"affected_regions\" : [ \"affected_regions\", \"affected_regions\" ], \"event_id\" : \"event_id\", \"is_active\" : true, \"era\" : \"era\", \"name\" : \"The DataKrash (2020)\", \"type\" : \"GLOBAL\", \"start_date\" : \"2000-01-23T04:56:07.000+00:00\" } ], \"current_era\" : \"current_era\", \"meta\" : { \"total\" : 156, \"has_next\" : true, \"page\" : 1, \"total_pages\" : 8, \"has_prev\" : false, \"page_size\" : 20 } }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    String PATH_GET_CHARACTER_AFFECTED_EVENTS = "/gameplay/world/events/character/{character_id}/affected";
    /**
     * GET /gameplay/world/events/character/{character_id}/affected : Получить события, влияющие на персонажа
     *
     * @param characterId  (required)
     * @return События, влияющие на персонажа (status code 200)
     */
    @Operation(
        operationId = "getCharacterAffectedEvents",
        summary = "Получить события, влияющие на персонажа",
        tags = { "World Events" },
        responses = {
            @ApiResponse(responseCode = "200", description = "События, влияющие на персонажа", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = GetCharacterAffectedEvents200Response.class))
            })
        },
        security = {
            @SecurityRequirement(name = "BearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = WorldEventsApi.PATH_GET_CHARACTER_AFFECTED_EVENTS,
        produces = { "application/json" }
    )
    default ResponseEntity<GetCharacterAffectedEvents200Response> getCharacterAffectedEvents(
        @NotNull @Parameter(name = "character_id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("character_id") UUID characterId
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"active_effects\" : [ { \"duration\" : \"duration\", \"stackable\" : true, \"modifier\" : { \"type\" : \"type\", \"value\" : 0.8008281904610115 }, \"description\" : \"description\", \"effect_type\" : \"ECONOMIC\", \"effect_id\" : \"effect_id\" }, { \"duration\" : \"duration\", \"stackable\" : true, \"modifier\" : { \"type\" : \"type\", \"value\" : 0.8008281904610115 }, \"description\" : \"description\", \"effect_type\" : \"ECONOMIC\", \"effect_id\" : \"effect_id\" } ] }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    String PATH_GET_ECONOMIC_MULTIPLIERS = "/gameplay/world/events/economy/multipliers";
    /**
     * GET /gameplay/world/events/economy/multipliers : Получить экономические множители от событий
     *
     * @return Экономические множители (status code 200)
     */
    @Operation(
        operationId = "getEconomicMultipliers",
        summary = "Получить экономические множители от событий",
        tags = { "World Events" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Экономические множители", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = EconomicMultipliers.class))
            })
        },
        security = {
            @SecurityRequirement(name = "BearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = WorldEventsApi.PATH_GET_ECONOMIC_MULTIPLIERS,
        produces = { "application/json" }
    )
    default ResponseEntity<EconomicMultipliers> getEconomicMultipliers(
        
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"currency_exchange_rates\" : { \"key\" : 6.027456183070403 }, \"price_multipliers\" : { \"weapons\" : 1.5, \"cyberware\" : 2.0, \"food\" : 0.8 }, \"trade_restrictions\" : [ { \"restriction_type\" : \"BANNED\", \"multiplier\" : 0.8008281904610115, \"item_category\" : \"item_category\" }, { \"restriction_type\" : \"BANNED\", \"multiplier\" : 0.8008281904610115, \"item_category\" : \"item_category\" } ] }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    String PATH_GET_WORLD_EVENT = "/gameplay/world/events/{event_id}";
    /**
     * GET /gameplay/world/events/{event_id} : Получить детали мирового события
     *
     * @param eventId  (required)
     * @return Детали события (status code 200)
     *         or Запрошенный ресурс не найден.  (status code 404)
     */
    @Operation(
        operationId = "getWorldEvent",
        summary = "Получить детали мирового события",
        tags = { "World Events" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Детали события", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = WorldEventDetailed.class))
            }),
            @ApiResponse(responseCode = "404", description = "Запрошенный ресурс не найден. ", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class), examples = {
                    @ExampleObject(
                        name = "",
                        value = "{\"error\":{\"code\":\"NOT_FOUND\",\"message\":\"Запрошенный ресурс не найден\",\"details\":[{\"field\":\"id\",\"message\":\"NPC с указанным ID не существует\",\"code\":\"RESOURCE_NOT_FOUND\"}]}}"
                    )
                })

            })
        },
        security = {
            @SecurityRequirement(name = "BearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = WorldEventsApi.PATH_GET_WORLD_EVENT,
        produces = { "application/json" }
    )
    default ResponseEntity<WorldEventDetailed> getWorldEvent(
        @NotNull @Parameter(name = "event_id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("event_id") String eventId
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"severity\" : \"MINOR\", \"end_date\" : \"2000-01-23T04:56:07.000+00:00\", \"affected_regions\" : [ \"affected_regions\", \"affected_regions\" ], \"is_active\" : true, \"faction_involvement\" : [ { \"role\" : \"INSTIGATOR\", \"faction\" : \"faction\" }, { \"role\" : \"INSTIGATOR\", \"faction\" : \"faction\" } ], \"description\" : \"description\", \"type\" : \"GLOBAL\", \"effects\" : [ { \"duration\" : \"duration\", \"stackable\" : true, \"modifier\" : { \"type\" : \"type\", \"value\" : 0.8008281904610115 }, \"description\" : \"description\", \"effect_type\" : \"ECONOMIC\", \"effect_id\" : \"effect_id\" }, { \"duration\" : \"duration\", \"stackable\" : true, \"modifier\" : { \"type\" : \"type\", \"value\" : 0.8008281904610115 }, \"description\" : \"description\", \"effect_type\" : \"ECONOMIC\", \"effect_id\" : \"effect_id\" } ], \"event_id\" : \"event_id\", \"quest_hooks\" : [ { \"trigger_condition\" : \"trigger_condition\", \"quest_id\" : \"quest_id\" }, { \"trigger_condition\" : \"trigger_condition\", \"quest_id\" : \"quest_id\" } ], \"era\" : \"era\", \"lore_background\" : \"lore_background\", \"name\" : \"The DataKrash (2020)\", \"start_date\" : \"2000-01-23T04:56:07.000+00:00\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"error\" : { \"code\" : \"VALIDATION_ERROR\", \"details\" : [ { \"code\" : \"code\", \"field\" : \"field\", \"message\" : \"message\" }, { \"code\" : \"code\", \"field\" : \"field\", \"message\" : \"message\" } ], \"message\" : \"Неверные параметры запроса\" } }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }

}
