// Code generated by ogen, DO NOT EDIT.

package api

// OperationName is the ogen operation name
type OperationName = string

const (
	AddItemOperation      OperationName = "AddItem"
	EquipItemOperation    OperationName = "EquipItem"
	GetEquipmentOperation OperationName = "GetEquipment"
	GetInventoryOperation OperationName = "GetInventory"
	GetItemOperation      OperationName = "GetItem"
	GetVaultOperation     OperationName = "GetVault"
	GetVaultsOperation    OperationName = "GetVaults"
	MoveItemOperation     OperationName = "MoveItem"
	RemoveItemOperation   OperationName = "RemoveItem"
	RetrieveItemOperation OperationName = "RetrieveItem"
	StoreItemOperation    OperationName = "StoreItem"
	UnequipItemOperation  OperationName = "UnequipItem"
	UpdateItemOperation   OperationName = "UpdateItem"
)
