// Code generated by ogen. DO NOT EDIT.
// Issue: #141889233

package api

import (
	"encoding/json"
	"fmt"
	"time"
)

// Error represents error response.
type Error struct {
	Message string `json:"message"`
	Code    string `json:"code,omitempty"`
	Details any    `json:"details,omitempty"`
}

func (e Error) Error() string {
	return e.Message
}

// NewError creates new error.
func NewError(code int, message string) error {
	return &Error{
		Code:    fmt.Sprintf("%d", code),
		Message: message,
	}
}

// HealthCheckResponse represents health check response.
type HealthCheckResponse struct {
	Status    string    `json:"status"` // "healthy" or "unhealthy"
	Service   string    `json:"service"`
	Timestamp time.Time `json:"timestamp"`
	Error     *Error    `json:"error,omitempty"`
}

// ReadinessCheckResponse represents readiness check response.
type ReadinessCheckResponse struct {
	Status    string    `json:"status"` // "ready" or "not_ready"
	Timestamp time.Time `json:"timestamp"`
	Error     *Error    `json:"error,omitempty"`
}

// GetStockChartParams represents parameters for GetStockChart.
type GetStockChartParams struct {
	Symbol    string
	Timeframe GetStockChartParamsTimeframe
	Limit     OptInt
}

// GetStockChartParamsTimeframe represents timeframe enum.
type GetStockChartParamsTimeframe string

const (
	GetStockChartParamsTimeframe1m  GetStockChartParamsTimeframe = "1m"
	GetStockChartParamsTimeframe5m  GetStockChartParamsTimeframe = "5m"
	GetStockChartParamsTimeframe15m GetStockChartParamsTimeframe = "15m"
	GetStockChartParamsTimeframe1h  GetStockChartParamsTimeframe = "1h"
	GetStockChartParamsTimeframe4h  GetStockChartParamsTimeframe = "4h"
	GetStockChartParamsTimeframe1d  GetStockChartParamsTimeframe = "1d"
	GetStockChartParamsTimeframe1w  GetStockChartParamsTimeframe = "1w"
	GetStockChartParamsTimeframe1M  GetStockChartParamsTimeframe = "1M"
)

// StockChartData represents stock chart data response.
type StockChartData struct {
	Symbol    string           `json:"symbol"`
	Timeframe string           `json:"timeframe"`
	Data      []ChartPoint     `json:"data"`
	Metadata  *ChartMetadata   `json:"metadata,omitempty"`
}

// ChartPoint represents a single chart data point.
type ChartPoint struct {
	Timestamp string  `json:"timestamp"`
	Open      float64 `json:"open"`
	High      float64 `json:"high"`
	Low       float64 `json:"low"`
	Close     float64 `json:"close"`
	Volume    int64   `json:"volume"`
}

// ChartMetadata represents chart metadata.
type ChartMetadata struct {
	TotalPoints  int    `json:"totalPoints"`
	DataQuality  string `json:"dataQuality"` // "high", "medium", "low"
	LastUpdated  string `json:"lastUpdated"`
}

// GetStockIndicatorsParams represents parameters for GetStockIndicators.
type GetStockIndicatorsParams struct {
	Symbol     string   `json:"symbol"`
	Indicators []string `json:"indicators"`
}

// StockIndicators represents technical indicators response.
type StockIndicators struct {
	Symbol     string             `json:"symbol"`
	Rsi        *RSIIndicator      `json:"rsi,omitempty"`
	Macd       *MACDIndicator     `json:"macd,omitempty"`
	Bollinger  *BollingerBands    `json:"bollinger,omitempty"`
}

// RSIIndicator represents RSI indicator data.
type RSIIndicator struct {
	Period int       `json:"period"`
	Values []float64 `json:"values"`
}

// MACDIndicator represents MACD indicator data.
type MACDIndicator struct {
	FastPeriod   int         `json:"fastPeriod"`
	SlowPeriod   int         `json:"slowPeriod"`
	SignalPeriod int         `json:"signalPeriod"`
	Values       []MACDValue `json:"values"`
}

// MACDValue represents single MACD value.
type MACDValue struct {
	Macd     float64 `json:"macd"`
	Signal   float64 `json:"signal"`
	Histogram float64 `json:"histogram"`
}

// BollingerBands represents Bollinger Bands indicator data.
type BollingerBands struct {
	Period    int       `json:"period"`
	Multiplier float64   `json:"multiplier"`
	Upper     []float64 `json:"upper"`
	Middle    []float64 `json:"middle"`
	Lower     []float64 `json:"lower"`
}

// MarketOverview represents market overview response.
type MarketOverview struct {
	MarketStatus     string         `json:"marketStatus"` // "open", "closed", "pre_market", "after_hours"
	MajorIndices     []IndexData    `json:"majorIndices,omitempty"`
	SectorPerformance []SectorData   `json:"sectorPerformance,omitempty"`
	VolumeLeaders    []StockVolumeData `json:"volumeLeaders,omitempty"`
}

// IndexData represents market index data.
type IndexData struct {
	Symbol        string  `json:"symbol"`
	Name          string  `json:"name"`
	Value         float64 `json:"value"`
	Change        float64 `json:"change"`
	ChangePercent float64 `json:"changePercent"`
}

// SectorData represents sector performance data.
type SectorData struct {
	Sector      string  `json:"sector"`
	Performance float64 `json:"performance"`
	Volume      int64   `json:"volume"`
}

// StockVolumeData represents stock volume data.
type StockVolumeData struct {
	Symbol string  `json:"symbol"`
	Volume int64   `json:"volume"`
	Price  float64 `json:"price"`
}

// CustomChartRequest represents custom chart creation request.
type CustomChartRequest struct {
	Symbol     string                    `json:"symbol"`
	ChartType  string                    `json:"chartType"` // "line", "candlestick", "bar", "area"
	Timeframe  string                    `json:"timeframe"`
	Indicators []string                  `json:"indicators,omitempty"`
	Style      *CustomChartStyle         `json:"style,omitempty"`
}

// CustomChartStyle represents custom chart styling.
type CustomChartStyle struct {
	Colors *ChartColors `json:"colors,omitempty"`
}

// ChartColors represents chart color scheme.
type ChartColors struct {
	Bullish string `json:"bullish,omitempty"`
	Bearish string `json:"bearish,omitempty"`
	Background string `json:"background,omitempty"`
}

// CustomChartResponse represents custom chart creation response.
type CustomChartResponse struct {
	ChartID   string    `json:"chartID"`
	Config    CustomChartRequest `json:"config"`
	CreatedAt string    `json:"createdAt"`
}

// StreamStockDataParams represents parameters for StreamStockData.
type StreamStockDataParams struct {
	Symbol string `json:"symbol"`
}

// OptInt represents optional integer.
type OptInt struct {
	Value int
	Set   bool
}

// Get returns value and presence flag.
func (o OptInt) Get() (int, bool) {
	return o.Value, o.Set
}

// Set sets value.
func (o *OptInt) Set(value int) {
	o.Value = value
	o.Set = true
}

// MarshalJSON implements json.Marshaler.
func (o OptInt) MarshalJSON() ([]byte, error) {
	if !o.Set {
		return []byte("null"), nil
	}
	return json.Marshal(o.Value)
}

// UnmarshalJSON implements json.Unmarshaler.
func (o *OptInt) UnmarshalJSON(data []byte) error {
	if string(data) == "null" {
		o.Set = false
		return nil
	}
	o.Set = true
	return json.Unmarshal(data, &o.Value)
}

// Issue: #141889233
