// Code generated by ogen, DO NOT EDIT.

package api

// setDefaults set default value of fields.
func (s *ActiveEffect) setDefaults() {
	{
		val := bool(false)
		s.IsExpired.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *EffectApplication) setDefaults() {
	{
		val := int(1)
		s.Stacks.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *EffectBase) setDefaults() {
	{
		val := int32(1)
		s.StackLimit = val
	}
}

// setDefaults set default value of fields.
func (s *EffectUpsertRequest) setDefaults() {
	{
		val := int32(1)
		s.StackLimit = val
	}
}

// setDefaults set default value of fields.
func (s *InteractionRule) setDefaults() {
	{
		val := float32(1)
		s.DamageMultiplier = val
	}
}

// setDefaults set default value of fields.
func (s *InteractionUpsertRequest) setDefaults() {
	{
		val := float32(1)
		s.DamageMultiplier = val
	}
}
