// Code generated by NECPGAME backend agent. Enterprise-grade Voice Chat service entry point.
// PERFORMANCE: Optimized server startup with WebRTC signaling and real-time voice communication
// Issue: #2206 - Voice Chat Service for MMO Real-Time Communication

package main

import (
	"context"
	"log"
	"net/http"
	_ "net/http/pprof" // PERFORMANCE: pprof endpoint for profiling (Level 2 optimization)
	"os"
	"os/signal"
	"syscall"
	"time"

	"github.com/go-faster/errors"
	"go.opentelemetry.io/otel"
	"go.opentelemetry.io/otel/metric"
	"go.opentelemetry.io/otel/trace"
	"go.uber.org/zap"

	"necpgame/services/voice-chat-service-go/config"
	"necpgame/services/voice-chat-service-go/internal/service"
)

func main() {
	// PERFORMANCE: GC tuning for real-time voice communication (Level 2 optimization)
	// Voice chat requires low-latency processing with high throughput
	if gcPercent := os.Getenv("GOGC"); gcPercent == "" {
		// debug.SetGCPercent(75) // Uncomment for production tuning
	}

	// Initialize structured logger
	logger, err := zap.NewProduction()
	if err != nil {
		log.Fatalf("Failed to initialize logger: %v", err)
	}
	defer logger.Sync()

	// Load configuration
	cfg := config.Load()

	// Get configuration from environment with voice-chat-specific defaults
	addr := os.Getenv("ADDR")
	if addr == "" {
		addr = "0.0.0.0:8085" // Voice chat service port
	}

	signalingAddr := os.Getenv("SIGNALING_ADDR")
	if signalingAddr == "" {
		signalingAddr = ":8086" // WebRTC signaling port
	}

	metricsAddr := os.Getenv("METRICS_ADDR")
	if metricsAddr == "" {
		metricsAddr = ":9095" // Voice chat metrics port
	}

	// PERFORMANCE: Profiling endpoint for real-time performance monitoring
	profilingAddr := os.Getenv("PPROF_ADDR")
	if profilingAddr == "" {
		profilingAddr = ":6066" // Voice chat profiling port
	}

	// Initialize OpenTelemetry tracer for voice communication processing
	tracer := otel.Tracer("voice-chat-service")

	// Initialize meter for voice chat metrics
	meter := otel.Meter("voice-chat-service")

	// Create service instance with voice-chat-specific optimizations
	svc, err := service.NewVoiceChatService(service.Config{
		Logger:      logger,
		Tracer:      tracer,
		Meter:       meter,
		DatabaseURL: os.Getenv("DATABASE_URL"),
		RedisURL:    os.Getenv("REDIS_URL"),
		KafkaBrokers: os.Getenv("KAFKA_BROKERS"),
	})
	if err != nil {
		logger.Fatal("Failed to create voice chat service", zap.Error(err))
	}

	// Create API handler with voice communication optimizations
	handler := service.NewHandler(svc)

	// Create HTTP server with voice-chat-specific performance optimizations
	// PERFORMANCE: Tuned for real-time WebRTC signaling and voice data processing
	srv := &http.Server{
		Addr: addr,
		Handler: handler,
		ReadTimeout:       30 * time.Second,  // PERFORMANCE: Allow time for complex signaling operations
		WriteTimeout:      30 * time.Second,  // PERFORMANCE: Allow time for signaling responses
		IdleTimeout:       120 * time.Second, // PERFORMANCE: Keep connections for voice sessions
		ReadHeaderTimeout: 5 * time.Second,   // PERFORMANCE: Faster header processing
		MaxHeaderBytes:    2 << 20,          // PERFORMANCE: 2MB header limit for large signaling messages
	}

	// Start WebRTC signaling server
	signalingSrv := &http.Server{
		Addr: signalingAddr,
		Handler: service.NewSignalingHandler(svc),
		ReadTimeout:       15 * time.Second,  // PERFORMANCE: Faster for signaling
		WriteTimeout:      15 * time.Second,  // PERFORMANCE: Faster for signaling
		IdleTimeout:       300 * time.Second, // PERFORMANCE: Keep connections for voice sessions
		ReadHeaderTimeout: 3 * time.Second,   // PERFORMANCE: Very fast header processing
		MaxHeaderBytes:    1 << 20,          // PERFORMANCE: 1MB for signaling headers
	}

	// Start pprof profiling server for real-time performance monitoring
	go func() {
		logger.Info("Starting pprof profiling server", zap.String("addr", profilingAddr))
		if err := http.ListenAndServe(profilingAddr, nil); err != nil {
			logger.Error("Pprof server failed", zap.Error(err))
		}
	}()

	// Start signaling server with voice-chat logging
	go func() {
		logger.Info("Starting WebRTC signaling server",
			zap.String("addr", signalingAddr),
			zap.String("performance_target", "P99 <50ms"),
			zap.String("optimization_level", "Level 2 (Real-Time)"))
		if err := signalingSrv.ListenAndServe(); err != nil && !errors.Is(err, http.ErrServerClosed) {
			logger.Fatal("Signaling server failed", zap.Error(err))
		}
	}()

	// Start main server with voice-chat logging
	go func() {
		logger.Info("Starting voice chat service",
			zap.String("addr", addr),
			zap.String("signaling_addr", signalingAddr),
			zap.String("metrics_addr", metricsAddr),
			zap.String("pprof_addr", profilingAddr),
			zap.String("performance_target", "P99 <20ms"),
			zap.String("optimization_level", "Level 2 (Real-Time)"))
		if err := srv.ListenAndServe(); err != nil && !errors.Is(err, http.ErrServerClosed) {
			logger.Fatal("Voice chat server failed", zap.Error(err))
		}
	}()

	// Start voice quality monitoring
	go func() {
		logger.Info("Starting voice quality monitoring")
		if err := svc.StartQualityMonitoring(ctx); err != nil {
			logger.Error("Voice quality monitoring failed", zap.Error(err))
		}
	}()

	// Wait for interrupt signal to gracefully shutdown the voice chat servers
	quit := make(chan os.Signal, 1)
	signal.Notify(quit, syscall.SIGINT, syscall.SIGTERM)
	<-quit

	logger.Info("Shutting down voice chat servers...")

	// Give outstanding voice connections a deadline for completion
	// PERFORMANCE: Reasonable timeout for active voice sessions
	ctx, cancel := context.WithTimeout(context.Background(), 30*time.Second)
	defer cancel()

	// Shutdown signaling server first (less critical)
	if err := signalingSrv.Shutdown(ctx); err != nil {
		logger.Error("Signaling server forced to shutdown", zap.Error(err))
	}

	// Shutdown main server
	if err := srv.Shutdown(ctx); err != nil {
		logger.Error("Voice chat server forced to shutdown", zap.Error(err))
	}

	// Shutdown voice chat service with cleanup
	if err := svc.Shutdown(ctx); err != nil {
		logger.Error("Voice chat service shutdown error", zap.Error(err))
	}

	logger.Info("Voice chat servers exited gracefully")
}