// Code generated by ogen, DO NOT EDIT.

package api

// setDefaults set default value of fields.
func (s *DamageModifier) setDefaults() {
	{
		val := int(1)
		s.Stacks.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *DotApplicationRequest) setDefaults() {
	{
		val := int(1000)
		s.TickIntervalMs.SetTo(val)
	}
	{
		val := int(1)
		s.MaxStacks.SetTo(val)
	}
	{
		val := bool(true)
		s.CanRefresh.SetTo(val)
	}
}
