// Code generated by ogen, DO NOT EDIT.

package api

// OperationName is the ogen operation name
type OperationName = string

const (
	GetFriendOperation        OperationName = "GetFriend"
	GetFriendsOperation       OperationName = "GetFriends"
	GetFriendsCountOperation  OperationName = "GetFriendsCount"
	GetOnlineFriendsOperation OperationName = "GetOnlineFriends"
	RemoveFriendOperation     OperationName = "RemoveFriend"
)
