// Code generated by ogen, DO NOT EDIT.
package api

type CreateExampleRes interface {
	createExampleRes()
}

type CustomizationServiceHealthCheckRes interface {
	customizationServiceHealthCheckRes()
}

type DeleteExampleRes interface {
	deleteExampleRes()
}

type ExampleDomainBatchHealthCheckRes interface {
	exampleDomainBatchHealthCheckRes()
}

type ExampleDomainHealthWebSocketRes interface {
	exampleDomainHealthWebSocketRes()
}

type GetExampleRes interface {
	getExampleRes()
}

type ListExamplesRes interface {
	listExamplesRes()
}

type UpdateExampleRes interface {
	updateExampleRes()
}
