// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// ClaimAttachments implements claimAttachments operation.
	//
	// Забрать вложения.
	//
	// POST /social/mail/{mail_id}/claim-attachments
	ClaimAttachments(ctx context.Context, params ClaimAttachmentsParams) (ClaimAttachmentsRes, error)
	// DeleteMail implements deleteMail operation.
	//
	// Удалить письмо.
	//
	// DELETE /social/mail/{mail_id}
	DeleteMail(ctx context.Context, params DeleteMailParams) (*SuccessResponse, error)
	// GetInbox implements getInbox operation.
	//
	// Получить входящие письма.
	//
	// GET /social/mail/inbox
	GetInbox(ctx context.Context, params GetInboxParams) (*InboxResponse, error)
	// GetMail implements getMail operation.
	//
	// Получить детали письма (помечает как прочитанное).
	//
	// GET /social/mail/{mail_id}
	GetMail(ctx context.Context, params GetMailParams) (GetMailRes, error)
	// SendMail implements sendMail operation.
	//
	// Отправить письмо.
	//
	// POST /social/mail/send
	SendMail(ctx context.Context, req *SendMailRequest) (SendMailRes, error)
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h   Handler
	sec SecurityHandler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, sec SecurityHandler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		sec:        sec,
		baseServer: s,
	}, nil
}
