// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// DistributeParagonPoints implements DistributeParagonPoints operation.
	//
	// Distribute paragon points.
	//
	// POST /paragon/distribute
	DistributeParagonPoints(ctx context.Context, req *DistributeParagonPointsReq) (DistributeParagonPointsRes, error)
	// GetMasteryLevels implements GetMasteryLevels operation.
	//
	// Get mastery levels.
	//
	// GET /mastery/levels
	GetMasteryLevels(ctx context.Context, params GetMasteryLevelsParams) (GetMasteryLevelsRes, error)
	// GetMasteryProgress implements GetMasteryProgress operation.
	//
	// Get mastery progress.
	//
	// GET /mastery/{type}/progress
	GetMasteryProgress(ctx context.Context, params GetMasteryProgressParams) (GetMasteryProgressRes, error)
	// GetMasteryRewards implements GetMasteryRewards operation.
	//
	// Get mastery rewards.
	//
	// GET /mastery/rewards
	GetMasteryRewards(ctx context.Context, params GetMasteryRewardsParams) (GetMasteryRewardsRes, error)
	// GetParagonLevels implements GetParagonLevels operation.
	//
	// Get paragon levels for character.
	//
	// GET /paragon/levels
	GetParagonLevels(ctx context.Context, params GetParagonLevelsParams) (GetParagonLevelsRes, error)
	// GetParagonStats implements GetParagonStats operation.
	//
	// Get paragon statistics.
	//
	// GET /paragon/stats
	GetParagonStats(ctx context.Context, params GetParagonStatsParams) (GetParagonStatsRes, error)
	// GetPrestigeBonuses implements GetPrestigeBonuses operation.
	//
	// Get prestige bonuses.
	//
	// GET /prestige/bonuses
	GetPrestigeBonuses(ctx context.Context, params GetPrestigeBonusesParams) (GetPrestigeBonusesRes, error)
	// GetPrestigeInfo implements GetPrestigeInfo operation.
	//
	// Get prestige information.
	//
	// GET /prestige/info
	GetPrestigeInfo(ctx context.Context, params GetPrestigeInfoParams) (GetPrestigeInfoRes, error)
	// HealthCheck implements HealthCheck operation.
	//
	// Service health check.
	//
	// GET /health
	HealthCheck(ctx context.Context) (HealthCheckRes, error)
	// ResetPrestige implements ResetPrestige operation.
	//
	// Reset prestige level.
	//
	// POST /prestige/reset
	ResetPrestige(ctx context.Context, req *ResetPrestigeReq) (ResetPrestigeRes, error)
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h   Handler
	sec SecurityHandler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, sec SecurityHandler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		sec:        sec,
		baseServer: s,
	}, nil
}
