// Code generated by ogen, DO NOT EDIT.
package api

type CreateCombatSessionRes interface {
	createCombatSessionRes()
}

type CreateSessionRes interface {
	createSessionRes()
}

type ExecuteCombatActionRes interface {
	executeCombatActionRes()
}

type GetCombatSessionStateRes interface {
	getCombatSessionStateRes()
}

type GetHealthRes interface {
	getHealthRes()
}

type GetSessionAnalyticsRes interface {
	getSessionAnalyticsRes()
}

type GetSessionRes interface {
	getSessionRes()
}

type ListCombatSessionsRes interface {
	listCombatSessionsRes()
}

type ListSessionsRes interface {
	listSessionsRes()
}

type TerminateSessionRes interface {
	terminateSessionRes()
}

type UpdateSessionRes interface {
	updateSessionRes()
}
