// Code generated by ogen, DO NOT EDIT.

package api

import (
	"net/http"
	"net/url"

	"github.com/go-faster/errors"
	"github.com/google/uuid"
	"github.com/ogen-go/ogen/conv"
	"github.com/ogen-go/ogen/middleware"
	"github.com/ogen-go/ogen/ogenerrors"
	"github.com/ogen-go/ogen/uri"
	"github.com/ogen-go/ogen/validate"
)

// DeleteAlertParams is parameters of deleteAlert operation.
type DeleteAlertParams struct {
	AlertID uuid.UUID
}

func unpackDeleteAlertParams(packed middleware.Parameters) (params DeleteAlertParams) {
	{
		key := middleware.ParameterKey{
			Name: "alert_id",
			In:   "path",
		}
		params.AlertID = packed[key].(uuid.UUID)
	}
	return params
}

func decodeDeleteAlertParams(args [1]string, argsEscaped bool, r *http.Request) (params DeleteAlertParams, _ error) {
	// Decode path: alert_id.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "alert_id",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToUUID(val)
				if err != nil {
					return err
				}

				params.AlertID = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "alert_id",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// GetHeatmapParams is parameters of getHeatmap operation.
type GetHeatmapParams struct {
	// Период (день, неделя, месяц).
	Period GetHeatmapPeriod
}

func unpackGetHeatmapParams(packed middleware.Parameters) (params GetHeatmapParams) {
	{
		key := middleware.ParameterKey{
			Name: "period",
			In:   "query",
		}
		params.Period = packed[key].(GetHeatmapPeriod)
	}
	return params
}

func decodeGetHeatmapParams(args [0]string, argsEscaped bool, r *http.Request) (params GetHeatmapParams, _ error) {
	q := uri.NewQueryDecoder(r.URL.Query())
	// Decode query: period.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "period",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.Period = GetHeatmapPeriod(c)
				return nil
			}); err != nil {
				return err
			}
			if err := func() error {
				if err := params.Period.Validate(); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return err
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "period",
			In:   "query",
			Err:  err,
		}
	}
	return params, nil
}

// GetOrderBookParams is parameters of getOrderBook operation.
type GetOrderBookParams struct {
	Ticker string
	// Глубина стакана (количество уровней).
	Depth OptInt `json:",omitempty,omitzero"`
}

func unpackGetOrderBookParams(packed middleware.Parameters) (params GetOrderBookParams) {
	{
		key := middleware.ParameterKey{
			Name: "ticker",
			In:   "path",
		}
		params.Ticker = packed[key].(string)
	}
	{
		key := middleware.ParameterKey{
			Name: "depth",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.Depth = v.(OptInt)
		}
	}
	return params
}

func decodeGetOrderBookParams(args [1]string, argsEscaped bool, r *http.Request) (params GetOrderBookParams, _ error) {
	q := uri.NewQueryDecoder(r.URL.Query())
	// Decode path: ticker.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "ticker",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.Ticker = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "ticker",
			In:   "path",
			Err:  err,
		}
	}
	// Set default value for query: depth.
	{
		val := int(10)
		params.Depth.SetTo(val)
	}
	// Decode query: depth.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "depth",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotDepthVal int
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToInt(val)
					if err != nil {
						return err
					}

					paramsDotDepthVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.Depth.SetTo(paramsDotDepthVal)
				return nil
			}); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "depth",
			In:   "query",
			Err:  err,
		}
	}
	return params, nil
}

// ListAlertsParams is parameters of listAlerts operation.
type ListAlertsParams struct {
	// Только активные алерты.
	ActiveOnly OptBool `json:",omitempty,omitzero"`
	// Количество элементов на странице.
	Limit OptInt `json:",omitempty,omitzero"`
	// Смещение для пагинации.
	Offset OptInt `json:",omitempty,omitzero"`
}

func unpackListAlertsParams(packed middleware.Parameters) (params ListAlertsParams) {
	{
		key := middleware.ParameterKey{
			Name: "active_only",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.ActiveOnly = v.(OptBool)
		}
	}
	{
		key := middleware.ParameterKey{
			Name: "limit",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.Limit = v.(OptInt)
		}
	}
	{
		key := middleware.ParameterKey{
			Name: "offset",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.Offset = v.(OptInt)
		}
	}
	return params
}

func decodeListAlertsParams(args [0]string, argsEscaped bool, r *http.Request) (params ListAlertsParams, _ error) {
	q := uri.NewQueryDecoder(r.URL.Query())
	// Set default value for query: active_only.
	{
		val := bool(true)
		params.ActiveOnly.SetTo(val)
	}
	// Decode query: active_only.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "active_only",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotActiveOnlyVal bool
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToBool(val)
					if err != nil {
						return err
					}

					paramsDotActiveOnlyVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.ActiveOnly.SetTo(paramsDotActiveOnlyVal)
				return nil
			}); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "active_only",
			In:   "query",
			Err:  err,
		}
	}
	// Set default value for query: limit.
	{
		val := int(50)
		params.Limit.SetTo(val)
	}
	// Decode query: limit.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "limit",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotLimitVal int
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToInt(val)
					if err != nil {
						return err
					}

					paramsDotLimitVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.Limit.SetTo(paramsDotLimitVal)
				return nil
			}); err != nil {
				return err
			}
			if err := func() error {
				if value, ok := params.Limit.Get(); ok {
					if err := func() error {
						if err := (validate.Int{
							MinSet:        true,
							Min:           1,
							MaxSet:        true,
							Max:           100,
							MinExclusive:  false,
							MaxExclusive:  false,
							MultipleOfSet: false,
							MultipleOf:    0,
							Pattern:       nil,
						}).Validate(int64(value)); err != nil {
							return errors.Wrap(err, "int")
						}
						return nil
					}(); err != nil {
						return err
					}
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "limit",
			In:   "query",
			Err:  err,
		}
	}
	// Set default value for query: offset.
	{
		val := int(0)
		params.Offset.SetTo(val)
	}
	// Decode query: offset.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "offset",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotOffsetVal int
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToInt(val)
					if err != nil {
						return err
					}

					paramsDotOffsetVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.Offset.SetTo(paramsDotOffsetVal)
				return nil
			}); err != nil {
				return err
			}
			if err := func() error {
				if value, ok := params.Offset.Get(); ok {
					if err := func() error {
						if err := (validate.Int{
							MinSet:        true,
							Min:           0,
							MaxSet:        false,
							Max:           0,
							MinExclusive:  false,
							MaxExclusive:  false,
							MultipleOfSet: false,
							MultipleOf:    0,
							Pattern:       nil,
						}).Validate(int64(value)); err != nil {
							return errors.Wrap(err, "int")
						}
						return nil
					}(); err != nil {
						return err
					}
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "offset",
			In:   "query",
			Err:  err,
		}
	}
	return params, nil
}
